# GENERATED FILE - do not edit by hand.
# generator: scripts/quality/generate_public_bindings.py
# generator-version: 1
# catalog-id: bb.public_operation_catalog.v2
# catalog-sha256: sha256:4deb87f3b82f7ccdf922fb609a9784840fb01ee591793e95f2af42acd2097674

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Mapping


@dataclass(frozen=True, slots=True)
class PublicOperationBinding:
    operation_id: str
    status: str
    http_method: str
    path: str
    cli_command: str
    python_client: str
    python_method: str
    typescript_client: str
    typescript_method: str
    action_id: str
    action_kind: str


PUBLIC_OPERATION_BINDINGS: Final[tuple[PublicOperationBinding, ...]] = (
    PublicOperationBinding(
        operation_id="artifact.get",
        status="candidate",
        http_method="GET",
        path="/v1/artifacts/{artifact_id}",
        cli_command="bbh artifact get",
        python_client="BreadBoardClient",
        python_method="get_artifact",
        typescript_client="BreadBoardClient",
        typescript_method="getArtifact",
        action_id="public.artifact.get",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="artifact.list",
        status="candidate",
        http_method="GET",
        path="/v1/artifacts",
        cli_command="bbh artifact list",
        python_client="BreadBoardClient",
        python_method="list_artifact",
        typescript_client="BreadBoardClient",
        typescript_method="listArtifact",
        action_id="public.artifact.list",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="artifact.verify",
        status="candidate",
        http_method="POST",
        path="/v1/artifacts/{artifact_id}/verify",
        cli_command="bbh artifact verify",
        python_client="BreadBoardClient",
        python_method="verify_artifact",
        typescript_client="BreadBoardClient",
        typescript_method="verifyArtifact",
        action_id="public.artifact.verify",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="harness.create",
        status="candidate",
        http_method="POST",
        path="/v1/harnesses",
        cli_command="bbh harness create",
        python_client="BreadBoardClient",
        python_method="create_harness",
        typescript_client="BreadBoardClient",
        typescript_method="createHarness",
        action_id="public.harness.create",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="harness.explain",
        status="candidate",
        http_method="POST",
        path="/v1/harnesses/{harness_id}/explain",
        cli_command="bbh harness explain",
        python_client="BreadBoardClient",
        python_method="explain_harness",
        typescript_client="BreadBoardClient",
        typescript_method="explainHarness",
        action_id="public.harness.explain",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="harness.get",
        status="candidate",
        http_method="GET",
        path="/v1/harnesses/{harness_id}",
        cli_command="bbh harness get",
        python_client="BreadBoardClient",
        python_method="get_harness",
        typescript_client="BreadBoardClient",
        typescript_method="getHarness",
        action_id="public.harness.get",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="harness.list",
        status="candidate",
        http_method="GET",
        path="/v1/harnesses",
        cli_command="bbh harness list",
        python_client="BreadBoardClient",
        python_method="list_harness",
        typescript_client="BreadBoardClient",
        typescript_method="listHarness",
        action_id="public.harness.list",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="harness.lock",
        status="candidate",
        http_method="POST",
        path="/v1/harnesses/{harness_id}/lock",
        cli_command="bbh harness lock",
        python_client="BreadBoardClient",
        python_method="lock_harness",
        typescript_client="BreadBoardClient",
        typescript_method="lockHarness",
        action_id="public.harness.lock",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="harness.update",
        status="candidate",
        http_method="PUT",
        path="/v1/harnesses/{harness_id}",
        cli_command="bbh harness update",
        python_client="BreadBoardClient",
        python_method="update_harness",
        typescript_client="BreadBoardClient",
        typescript_method="updateHarness",
        action_id="public.harness.update",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="harness.validate",
        status="candidate",
        http_method="POST",
        path="/v1/harnesses/{harness_id}/validate",
        cli_command="bbh harness validate",
        python_client="BreadBoardClient",
        python_method="validate_harness",
        typescript_client="BreadBoardClient",
        typescript_method="validateHarness",
        action_id="public.harness.validate",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="harness_lock.get",
        status="candidate",
        http_method="GET",
        path="/v1/harness-locks/{lock_id}",
        cli_command="bbh harness-lock get",
        python_client="BreadBoardClient",
        python_method="get_harness_lock",
        typescript_client="BreadBoardClient",
        typescript_method="getHarnessLock",
        action_id="public.harness_lock.get",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="integration.get",
        status="candidate",
        http_method="GET",
        path="/v1/integrations/{integration_id}",
        cli_command="bbh integration get",
        python_client="BreadBoardClient",
        python_method="get_integration",
        typescript_client="BreadBoardClient",
        typescript_method="getIntegration",
        action_id="public.integration.get",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="integration.list",
        status="candidate",
        http_method="GET",
        path="/v1/integrations",
        cli_command="bbh integration list",
        python_client="BreadBoardClient",
        python_method="list_integration",
        typescript_client="BreadBoardClient",
        typescript_method="listIntegration",
        action_id="public.integration.list",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="integration.probe",
        status="candidate",
        http_method="POST",
        path="/v1/integrations/{integration_id}/probe",
        cli_command="bbh integration probe",
        python_client="BreadBoardClient",
        python_method="probe_integration",
        typescript_client="BreadBoardClient",
        typescript_method="probeIntegration",
        action_id="public.integration.probe",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="session.approve",
        status="candidate",
        http_method="POST",
        path="/v1/sessions/{session_id}/approve",
        cli_command="bbh session approve",
        python_client="BreadBoardClient",
        python_method="approve_session",
        typescript_client="BreadBoardClient",
        typescript_method="approveSession",
        action_id="public.session.approve",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="session.artifacts",
        status="candidate",
        http_method="GET",
        path="/v1/sessions/{session_id}/artifacts",
        cli_command="bbh session artifacts",
        python_client="BreadBoardClient",
        python_method="artifacts_session",
        typescript_client="BreadBoardClient",
        typescript_method="artifactsSession",
        action_id="public.session.artifacts",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="session.cancel",
        status="candidate",
        http_method="POST",
        path="/v1/sessions/{session_id}/cancel",
        cli_command="bbh session cancel",
        python_client="BreadBoardClient",
        python_method="cancel_session",
        typescript_client="BreadBoardClient",
        typescript_method="cancelSession",
        action_id="public.session.cancel",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="session.events",
        status="candidate",
        http_method="GET",
        path="/v1/sessions/{session_id}/events",
        cli_command="bbh session events",
        python_client="BreadBoardClient",
        python_method="events_session",
        typescript_client="BreadBoardClient",
        typescript_method="eventsSession",
        action_id="public.session.events",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="session.get",
        status="candidate",
        http_method="GET",
        path="/v1/sessions/{session_id}",
        cli_command="bbh session get",
        python_client="BreadBoardClient",
        python_method="get_session",
        typescript_client="BreadBoardClient",
        typescript_method="getSession",
        action_id="public.session.get",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="session.list",
        status="candidate",
        http_method="GET",
        path="/v1/sessions",
        cli_command="bbh session list",
        python_client="BreadBoardClient",
        python_method="list_session",
        typescript_client="BreadBoardClient",
        typescript_method="listSession",
        action_id="public.session.list",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="session.resume",
        status="candidate",
        http_method="POST",
        path="/v1/sessions/{session_id}/resume",
        cli_command="bbh session resume",
        python_client="BreadBoardClient",
        python_method="resume_session",
        typescript_client="BreadBoardClient",
        typescript_method="resumeSession",
        action_id="public.session.resume",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="session.send_input",
        status="candidate",
        http_method="POST",
        path="/v1/sessions/{session_id}/input",
        cli_command="bbh session send-input",
        python_client="BreadBoardClient",
        python_method="send_input_session",
        typescript_client="BreadBoardClient",
        typescript_method="sendInputSession",
        action_id="public.session.send_input",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="session.start",
        status="candidate",
        http_method="POST",
        path="/v1/sessions",
        cli_command="bbh harness run",
        python_client="BreadBoardClient",
        python_method="start_session",
        typescript_client="BreadBoardClient",
        typescript_method="startSession",
        action_id="public.session.start",
        action_kind="action",
    ),
    PublicOperationBinding(
        operation_id="system.describe",
        status="candidate",
        http_method="GET",
        path="/v1/system",
        cli_command="bbh system describe",
        python_client="BreadBoardClient",
        python_method="describe_system",
        typescript_client="BreadBoardClient",
        typescript_method="describeSystem",
        action_id="public.system.describe",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="system.health",
        status="candidate",
        http_method="GET",
        path="/v1/health",
        cli_command="bbh system health",
        python_client="BreadBoardClient",
        python_method="health_system",
        typescript_client="BreadBoardClient",
        typescript_method="healthSystem",
        action_id="public.system.health",
        action_kind="view",
    ),
    PublicOperationBinding(
        operation_id="system.schemas",
        status="candidate",
        http_method="GET",
        path="/v1/schemas",
        cli_command="bbh system schemas",
        python_client="BreadBoardClient",
        python_method="schemas_system",
        typescript_client="BreadBoardClient",
        typescript_method="schemasSystem",
        action_id="public.system.schemas",
        action_kind="view",
    ),
)

PUBLIC_BINDINGS_BY_OPERATION_ID: Final[Mapping[str, PublicOperationBinding]] = (
    MappingProxyType(
        {
            "artifact.get": PUBLIC_OPERATION_BINDINGS[0],
            "artifact.list": PUBLIC_OPERATION_BINDINGS[1],
            "artifact.verify": PUBLIC_OPERATION_BINDINGS[2],
            "harness.create": PUBLIC_OPERATION_BINDINGS[3],
            "harness.explain": PUBLIC_OPERATION_BINDINGS[4],
            "harness.get": PUBLIC_OPERATION_BINDINGS[5],
            "harness.list": PUBLIC_OPERATION_BINDINGS[6],
            "harness.lock": PUBLIC_OPERATION_BINDINGS[7],
            "harness.update": PUBLIC_OPERATION_BINDINGS[8],
            "harness.validate": PUBLIC_OPERATION_BINDINGS[9],
            "harness_lock.get": PUBLIC_OPERATION_BINDINGS[10],
            "integration.get": PUBLIC_OPERATION_BINDINGS[11],
            "integration.list": PUBLIC_OPERATION_BINDINGS[12],
            "integration.probe": PUBLIC_OPERATION_BINDINGS[13],
            "session.approve": PUBLIC_OPERATION_BINDINGS[14],
            "session.artifacts": PUBLIC_OPERATION_BINDINGS[15],
            "session.cancel": PUBLIC_OPERATION_BINDINGS[16],
            "session.events": PUBLIC_OPERATION_BINDINGS[17],
            "session.get": PUBLIC_OPERATION_BINDINGS[18],
            "session.list": PUBLIC_OPERATION_BINDINGS[19],
            "session.resume": PUBLIC_OPERATION_BINDINGS[20],
            "session.send_input": PUBLIC_OPERATION_BINDINGS[21],
            "session.start": PUBLIC_OPERATION_BINDINGS[22],
            "system.describe": PUBLIC_OPERATION_BINDINGS[23],
            "system.health": PUBLIC_OPERATION_BINDINGS[24],
            "system.schemas": PUBLIC_OPERATION_BINDINGS[25],
        }
    )
)

__all__ = [
    "PublicOperationBinding",
    "PUBLIC_OPERATION_BINDINGS",
    "PUBLIC_BINDINGS_BY_OPERATION_ID",
]
