// Run under the frozen-lock-installed OMP 18.1.17 source tree on Linux.
// The loader changes only the observations: it throws at the branch already
// selected by the sha-verified supplier ReadTool, before effects can run.
import { readFile, realpath } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const [sourceRoot, workspace, corpusFile, previousFile, outputFile, nativeConfigFile] = process.argv.slice(2);
if (!sourceRoot || !workspace || !corpusFile || !previousFile || !outputFile || !nativeConfigFile) {
  throw new Error("usage: oracle <source-root> <workspace> <inputs.json> <old.jsonl> <out.json> <native-config.json>");
}
const sourceSha = "270694388f57680524c3df3f6223e845dc8c4d78e2146748d2013c63ae9ba935";
const config = JSON.parse(await readFile(nativeConfigFile, "utf8"));
const classifier = config.route_classifier;
const hash = (bytes: Buffer) => createHash("sha256").update(bytes).digest("hex");
for (const { path, sha256 } of [...Object.values(classifier.modules), { path: "bun.lock", sha256: classifier.lock_sha256 }] as Array<{ path: string; sha256: string }>) {
  if (hash(await readFile(resolve(sourceRoot, path))) !== sha256.replace(/^sha256:/, "")) {
    throw new Error(`supplier module digest mismatch: ${path}`);
  }
}
const readSource = await realpath(resolve(sourceRoot, "packages/coding-agent/src/tools/read.ts"));
if (hash(await readFile(readSource)) !== sourceSha) throw new Error("supplier ReadTool digest mismatch");

// Each insertion sits inside a supplier-selected branch, not in a duplicate
// predicate. Reject a source revision that no longer has precisely that branch.
const branchMarkers = [
  ["if (parsedUrlTarget) {", "url"],
  ["return this.#handleInternalUrl(internalTarget.path, parsed, signal);", "internal"],
  ["if (archivePath) {", "archive"],
  ["if (sqlitePath) {", "sqlite"],
  ["if (isDirectory) {", "file"],
  ["if (pdfImageRead) {", "pdf"],
  ["if (isVideoPath(absolutePath)) {", "video"],
  ["if (parsed.kind === \"image\") {", "image"],
  ["} else if (mimeType) {", "image"],
  ["} else if (shouldConvertWithMarkit) {", "document"],
  ["// One read for every consumer below.", "file"],
  ["throw new ToolError(`Path '${localReadPath}' not found`);", "file"],
] as const;
const observedMarker = "__OMP_PINNED_ROUTE__:";
Bun.plugin({
  name: "sha-verified-pinned-read-branch-observer",
  setup(build) {
    build.onLoad({ filter: /\/tools\/read\.ts$/ }, async ({ path }) => {
      if (resolve(path) !== readSource) throw new Error("unexpected read dispatcher path");
      let contents = await readFile(readSource, "utf8");
      if (hash(Buffer.from(contents)) !== sourceSha) throw new Error("supplier ReadTool changed after verification");
      for (const [needle, route] of branchMarkers) {
        const occurrences = contents.split(needle).length - 1;
        const expected = route === "internal" ? 2 : 1;
        if (occurrences !== expected) throw new Error(`ambiguous supplier branch (${occurrences}): ${needle}`);
        const observation = route === "internal"
          ? `throw new Error("${observedMarker}" + (scheme === "ssh" ? "ssh" : "internal"));`
          : `throw new Error("${observedMarker}${route}");`;
        contents = contents.replaceAll(needle, needle.endsWith("{") ? `${needle}\n${observation}` : `${observation}\n${needle}`);
      }
      return { contents, loader: "ts" };
    });
  },
});

const { createAgentSession, Settings } = await import(`${sourceRoot}/packages/coding-agent/src/sdk.ts`);
const { SessionManager } = await import(`${sourceRoot}/packages/coding-agent/src/session/session-manager.ts`);
const settings = await Settings.init({ cwd: workspace, agentDir: resolve(workspace, ".oracle"), inMemory: true, configFiles: [], overrides: {
  "retry.enabled": false, "retry.fallbackChains": {}, "compaction.enabled": false,
  "modelLoopGuard.enabled": false, "tools.maxTimeout": 30, "edit.fuzzyMatch": true,
  "edit.fuzzyThreshold": 0.95, "edit.enforceSeenLines": true,
  "edit.autoRepair.enabled": false, "edit.blockAutoGenerated": true,
  "shellMinimizer.enabled": false,
} });
const created = await createAgentSession({
  cwd: workspace, agentDir: resolve(workspace, ".oracle"), modelPattern: "capture/capture", thinkingLevel: "off",
  toolNames: ["read", "bash", "edit", "write"], restrictToolNames: true, allowRestrictedCustomTools: false,
  settings, sessionManager: SessionManager.inMemory(workspace), contextFiles: [], skills: [], rules: [],
  promptTemplates: [], slashCommands: [], customTools: [], extensions: [], additionalExtensionPaths: [],
  disableExtensionDiscovery: true, enableMCP: false, enableLsp: false, enableIrc: false,
  skipPythonPreflight: true, hasUI: false, interactivePrompts: false,
  rebindModelAfterDiscovery: false, getApiKey: async () => "omp-read-oracle-key",
});
const read = created.session.agent.state.tools.find((tool: { name: string }) => tool.name === "read");
if (!read) throw new Error("pinned SDK has no ReadTool");
const inputs: string[] = JSON.parse(await readFile(corpusFile, "utf8"));
const previous = (await readFile(previousFile, "utf8")).trim().split("\n").map(row => JSON.parse(row));
if (inputs.length !== previous.length || inputs.some((value, i) => value !== previous[i].input)) {
  throw new Error("oracle and corpus input order differ");
}
const rows: Array<{ input: string; route: string; previous: string; failure?: string }> = new Array(inputs.length);
for (let offset = 0; offset < inputs.length; offset += 72) {
  await Promise.all(inputs.slice(offset, offset + 72).map(async (input, batchIndex) => {
    const index = offset + batchIndex;
    let route = "unclassified";
    let failure: string | undefined;
    try {
      const result = await read.execute(`oracle-${index}`, { path: input });
      failure = `returned ${JSON.stringify({ details: result.details, content: result.content }).slice(0, 380)}`;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.startsWith(observedMarker)) route = message.slice(observedMarker.length);
      else failure = message;
    }
    rows[index] = { input, route, previous: previous[index].route, ...(failure ? { failure } : {}) };
  }));
}
const changes = rows.flatMap((row, index) =>
  row.route === row.previous ? [] : [{ index, input: row.input, pinned: row.route, previous: row.previous }]
);
const report = {
  label: "local-vm-linux", source_sha256: sourceSha,
  corpus_sha256: hash(await readFile(corpusFile)), count: rows.length,
  changes, rows,
};
await Bun.write(outputFile, JSON.stringify(report) + "\n");
console.log(JSON.stringify({ count: rows.length, disagreements: changes.length, unclassified: rows.filter(row => row.route === "unclassified").length }));
