#!/opt/omp/runtime/bun-linux-x64-baseline/bun
// Tool-only composition for OMP 18.1.17. This intentionally never calls
// session.prompt: the BreadBoard controller owns the model loop and transport.
const sourceRoot = "/opt/omp/source/oh-my-pi-3b3a6dc9bbd85102ce19d0b1c11bf6870915f6ec";
const { createAgentSession, Settings } = await import(`${sourceRoot}/packages/coding-agent/src/sdk.ts`);
const { SessionManager } = await import(`${sourceRoot}/packages/coding-agent/src/session/session-manager.ts`);

const args = Bun.argv.slice(2);
const arg = (name: string, fallback?: string): string => {
  const index = args.indexOf(name);
  return index >= 0 && args[index + 1] ? args[index + 1] : (fallback ?? "");
};
const cwd = arg("--cwd", process.cwd());
const agentDir = arg("--agent-dir", `${cwd}/.omp-agent`);
const settings = await Settings.init({ cwd, agentDir, inMemory: true, configFiles: [], overrides: {
  "retry.enabled": false,
  "retry.fallbackChains": {},
  "compaction.enabled": false,
  "modelLoopGuard.enabled": false,
  "tools.maxTimeout": 30,
  "edit.fuzzyMatch": true,
  "edit.fuzzyThreshold": 0.95,
  "edit.enforceSeenLines": true,
  "edit.autoRepair.enabled": false,
  "edit.blockAutoGenerated": true,
  "shellMinimizer.enabled": false,
} });
const sessionManager = SessionManager.inMemory(cwd);
const { session } = await createAgentSession({
  cwd,
  agentDir,
  modelPattern: "capture/capture",
  thinkingLevel: "off",
  toolNames: ["read", "bash", "edit", "write"],
  restrictToolNames: true,
  allowRestrictedCustomTools: false,
  settings,
  sessionManager,
  contextFiles: [], skills: [], rules: [], promptTemplates: [], slashCommands: [],
  customTools: [], extensions: [], additionalExtensionPaths: [],
  disableExtensionDiscovery: true, enableMCP: false, enableLsp: false,
  enableIrc: false, skipPythonPreflight: true, hasUI: false,
  interactivePrompts: false, rebindModelAfterDiscovery: false,
  getApiKey: async () => "omp-tool-worker-key",
});

const allowed = new Set(["read", "bash", "edit", "write"]);
const encoder = new TextEncoder();
const input = await new Response(Bun.stdin.stream()).text();
for (const line of input.split("\n")) {
  if (!line.trim()) continue;
  const call = JSON.parse(line) as { id: string; name: string; arguments: Record<string, unknown> };
  const tool = session.agent.state.tools.find(candidate => candidate.name === call.name);
  if (!allowed.has(call.name) || !tool) throw new Error(`OMP tool is not admitted: ${call.name}`);
  const result = await tool.execute(call.id, call.arguments);
  await Bun.write(Bun.stdout, encoder.encode(JSON.stringify({ id: call.id, name: call.name, result }) + "\n"));
}
await session.dispose();
