#!/opt/omp/runtime/bun-linux-x64-baseline/bun
// Persistent tool-only phase worker. The Conductor owns provider transport and
// the model loop; this process only composes and executes the four SDK tools.
const RPC_SCHEMA = "bb.native-worker.rpc.v1";
const PHASE_SCHEMA = "bb.omp-native.v1";
const SOURCE_ROOT = "/opt/omp/source/oh-my-pi-3b3a6dc9bbd85102ce19d0b1c11bf6870915f6ec";
const TOOL_NAMES = ["read", "bash", "edit", "write"] as const;
let boundedDescriptions: Record<string, string> = {};


type Call = { id: string; name: string; arguments: Record<string, unknown> };
let session: any = null;
let tools: any[] = [];
let prepared: Array<Call & { error?: string }> = [];
let workspace = "";

async function initialize(payload: Record<string, any>) {
  if (payload.workspace === undefined || payload.scratch === undefined) throw new Error("initialize requires injected workspace and scratch");
  workspace = String(payload.workspace);
  const descriptions = payload.advertisement?.tool_descriptions;
  if (descriptions && typeof descriptions === "object" && !Array.isArray(descriptions)) {
    boundedDescriptions = Object.fromEntries(
      Object.entries(descriptions).filter((entry): entry is [string, string] => typeof entry[1] === "string"),
    );
  }
  // The pinned source root is deployment-selected; static source imports cannot
  // represent the verified runtime path used by the SIF installation.
  const { createAgentSession, Settings } = await import(`${SOURCE_ROOT}/packages/coding-agent/src/sdk.ts`);
  const { SessionManager } = await import(`${SOURCE_ROOT}/packages/coding-agent/src/session/session-manager.ts`);
  const settings = await Settings.init({ cwd: workspace, agentDir: String(payload.scratch), inMemory: true, configFiles: [], overrides: {
    "retry.enabled": false, "retry.fallbackChains": {}, "compaction.enabled": false,
    "modelLoopGuard.enabled": false, "tools.maxTimeout": 30, "edit.fuzzyMatch": true,
    "edit.fuzzyThreshold": 0.95, "edit.enforceSeenLines": true, "edit.autoRepair.enabled": false,
    "edit.blockAutoGenerated": true, "shellMinimizer.enabled": false,
  } });
  const manager = SessionManager.inMemory(workspace);
  const created = await createAgentSession({
    cwd: workspace, agentDir: String(payload.scratch), modelPattern: "capture/capture", thinkingLevel: "off",
    toolNames: [...TOOL_NAMES], restrictToolNames: true, allowRestrictedCustomTools: false,
    settings, sessionManager: manager, contextFiles: [], skills: [], rules: [], promptTemplates: [],
    slashCommands: [], customTools: [], extensions: [], additionalExtensionPaths: [],
    disableExtensionDiscovery: true, enableMCP: false, enableLsp: false, enableIrc: false,
    skipPythonPreflight: true, hasUI: false, interactivePrompts: false,
    rebindModelAfterDiscovery: false, getApiKey: async () => "omp-tool-worker-key",
  });
  session = created.session;
  tools = session.agent.state.tools.filter((tool: any) => TOOL_NAMES.includes(tool.name));
  return {
    schema_version: PHASE_SCHEMA,
    kind: "initialized",
    system_prompt: String(payload.advertisement?.system_prompt ?? ""),
    tool_schemas: tools.map((tool: any) => ({ type: "function", function: { name: tool.name, description: boundedDescriptions[tool.name] ?? String(tool.description ?? ""), parameters: tool.parameters } })),
    bootstrap: { consumer_id: "breadboard.oh-my-pi.v18.1.17", workspace, source_commit: SOURCE_ROOT.split("-").at(-1), settings: payload.advertisement?.settings ?? {} },
  };
}

async function dispatch(operation: string, payload: Record<string, any>): Promise<Record<string, any>> {
  if (operation === "initialize") return initialize(payload);
  if (!session) throw new Error("worker must be initialized before phases");
  if (operation === "project_request") return { schema_version: PHASE_SCHEMA, kind: "request", messages: payload.messages ?? [], tools: tools.map((tool: any) => ({ type: "function", function: { name: tool.name, description: boundedDescriptions[tool.name] ?? String(tool.description ?? ""), parameters: tool.parameters } })) };
  if (operation === "prepare_tools") {
    prepared = (payload.calls ?? []).map((call: any) => {
      const item: any = { id: String(call.id), name: String(call.name), arguments: call.arguments };
      if (!TOOL_NAMES.includes(item.name)) item.error = `OMP tool is not admitted: ${item.name}`;
      if (!item.arguments || typeof item.arguments !== "object" || Array.isArray(item.arguments)) item.error = item.error ?? "Invalid tool arguments: expected a JSON object";
      return item;
    });
    return { schema_version: PHASE_SCHEMA, kind: "prepared", calls: prepared, history_calls: prepared.map((call) => ({ id: call.id, name: call.name, arguments: call.arguments })) };
  }
  if (operation === "execute_batch") {
    const completed: Array<Record<string, unknown> & { source_index: number }> = [];
    await Promise.all(prepared.map(async (call, sourceIndex) => {
      if (call.error) {
        completed.push({ id: call.id, completion_index: completed.length, content: call.error, details: { phase: "prepare" }, isError: true, source_index: sourceIndex });
        return;
      }
      const tool = tools.find((candidate: any) => candidate.name === call.name);
      if (!tool) {
        completed.push({ id: call.id, completion_index: completed.length, content: `OMP tool is not admitted: ${call.name}`, details: {}, isError: true, source_index: sourceIndex });
        return;
      }
      try {
        const result = await tool.execute(call.id, call.arguments);
        completed.push({ id: call.id, completion_index: completed.length, content: result.content ?? [], details: result.details ?? {}, isError: Boolean(result.details?.isError), terminate: Boolean(result.details?.terminate), source_index: sourceIndex });
      } catch (error) {
        completed.push({ id: call.id, completion_index: completed.length, content: String(error), details: { phase: "execute" }, isError: true, source_index: sourceIndex });
      }
    }));
    completed.sort((left, right) => left.source_index - right.source_index);
    return { schema_version: PHASE_SCHEMA, kind: "tool_results", results: completed.map(({ source_index, ...result }) => result) };
  }
  if (operation === "close") {
    await session.dispose();
    session = null;
    tools = [];
    return { schema_version: PHASE_SCHEMA, kind: "closed", cleanup: { processes: [], all_dead: true } };
  }
  throw new Error(`unknown OMP phase: ${operation}`);
}

const decoder = new TextDecoder();
const reader = Bun.stdin.stream().getReader();
let buffer = new Uint8Array(0);
function append(chunk: Uint8Array) { const next = new Uint8Array(buffer.length + chunk.length); next.set(buffer); next.set(chunk, buffer.length); buffer = next; }
async function writeFrame(value: Record<string, any>) {
  const encoded = new TextEncoder().encode(JSON.stringify(value));
  const frame = new Uint8Array(4 + encoded.length);
  new DataView(frame.buffer).setUint32(0, encoded.length, false);
  frame.set(encoded, 4);
  await Bun.write(Bun.stdout, frame);
}
while (true) {
  const { value, done } = await reader.read();
  if (done) break;
  append(value);
  while (buffer.length >= 4) {
    const length = new DataView(buffer.buffer, buffer.byteOffset, 4).getUint32(0, false);
    if (buffer.length < 4 + length) break;
    const payload = JSON.parse(decoder.decode(buffer.slice(4, 4 + length)));
    buffer = buffer.slice(4 + length);
    if (payload.schema_version !== RPC_SCHEMA || typeof payload.request_id !== "number") throw new Error("invalid worker frame");
    try {
      const result = await dispatch(payload.operation, payload.payload);
      await writeFrame({ schema_version: RPC_SCHEMA, request_id: payload.request_id, result });
    } catch (error) {
      await writeFrame({ schema_version: RPC_SCHEMA, request_id: payload.request_id, error: { type: "WorkerPhaseError", message: String(error) } });
    }
  }
}
