"""Opt-in search runtime primitives for DAG-shaped TTC research."""

from .compaction import (
    CompactionOutput,
    RegisteredCompactionBackend,
    SearchCompactionRegistry,
    build_default_search_compaction_registry,
)
from .examples import (
    build_pacore_search_runtime_example,
    build_pacore_search_runtime_example_payload,
    build_rsa_search_runtime_example,
    build_rsa_search_runtime_example_payload,
    build_search_trajectory_export_example,
    build_search_trajectory_export_example_payload,
    build_stateful_branch_search_example,
    build_stateful_branch_search_example_payload,
    build_typed_compaction_registry_example,
    build_typed_compaction_registry_example_payload,
)
from .export import (
    SearchOfflineDataset,
    SearchRewardSignal,
    SearchTrajectoryExport,
    SearchTrajectoryStep,
    build_default_reward_signals,
    build_search_offline_dataset,
    export_search_trajectory,
)
from .runtime import (
    AggregationProposal,
    BarrieredRoundScheduler,
    BarrieredSchedulerConfig,
    BoundedMessagePassingScheduler,
    MessagePassingSchedulerConfig,
)
from .schema import (
    ALLOWED_CANDIDATE_STATUSES,
    ALLOWED_FRONTIER_STATUSES,
    ALLOWED_OPERATOR_KINDS,
    ALLOWED_BRANCH_STATUSES,
    SearchBranchState,
    SearchCandidate,
    SearchCarryState,
    SearchEvent,
    SearchFrontier,
    SearchMessage,
    SearchMetrics,
    SearchRun,
    SearchWorkspaceSnapshot,
)

__all__ = [
    "ALLOWED_BRANCH_STATUSES",
    "ALLOWED_CANDIDATE_STATUSES",
    "ALLOWED_FRONTIER_STATUSES",
    "ALLOWED_OPERATOR_KINDS",
    "AggregationProposal",
    "BarrieredRoundScheduler",
    "BarrieredSchedulerConfig",
    "BoundedMessagePassingScheduler",
    "CompactionOutput",
    "MessagePassingSchedulerConfig",
    "RegisteredCompactionBackend",
    "SearchOfflineDataset",
    "SearchBranchState",
    "SearchCandidate",
    "SearchCarryState",
    "SearchCompactionRegistry",
    "SearchEvent",
    "SearchFrontier",
    "SearchMessage",
    "SearchMetrics",
    "SearchRewardSignal",
    "SearchRun",
    "SearchTrajectoryExport",
    "SearchTrajectoryStep",
    "SearchWorkspaceSnapshot",
    "build_default_reward_signals",
    "build_default_search_compaction_registry",
    "build_pacore_search_runtime_example",
    "build_pacore_search_runtime_example_payload",
    "build_rsa_search_runtime_example",
    "build_rsa_search_runtime_example_payload",
    "build_search_offline_dataset",
    "build_search_trajectory_export_example",
    "build_search_trajectory_export_example_payload",
    "build_stateful_branch_search_example",
    "build_stateful_branch_search_example_payload",
    "build_typed_compaction_registry_example",
    "build_typed_compaction_registry_example_payload",
    "export_search_trajectory",
]
