#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DOC = ROOT / "docs" / "contracts" / "E4_CONSUMPTION.md"
DEFAULT_RESULTS = ROOT / "docs" / "contracts" / "E4_CONSUMPTION_DOCTEST_RESULTS.md"
FENCE_RE = re.compile(r"```(?P<lang>bash|sh)\n(?P<body>.*?)\n```", re.DOTALL)


@dataclass(frozen=True)
class CommandBlock:
    index: int
    language: str
    command: str


def command_blocks(markdown: str) -> list[CommandBlock]:
    blocks: list[CommandBlock] = []
    for match in FENCE_RE.finditer(markdown):
        blocks.append(CommandBlock(index=len(blocks) + 1, language=match.group("lang"), command=match.group("body").strip()))
    return blocks


def run_block(block: CommandBlock) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        block.command,
        cwd=ROOT,
        shell=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=120,
        executable="/bin/bash",
        check=False,
    )


def first_lines(text: str, limit: int = 20) -> str:
    lines = text.splitlines()[:limit]
    return "\n".join(lines) if lines else "(no output)"


def write_results(path: Path, results: list[tuple[CommandBlock, subprocess.CompletedProcess[str]]]) -> None:
    lines = ["# E4 consumption doctest results", "", "Generated by `scripts/e4_parity/doctest_e4_consumption.py`.", ""]
    for block, completed in results:
        lines.extend(
            [
                f"## Command {block.index}",
                "",
                "```bash",
                block.command,
                "```",
                "",
                f"Exit code: `{completed.returncode}`",
                "",
                "First output lines:",
                "",
                "```text",
                first_lines(completed.stdout),
                "```",
                "",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Execute bash/sh command fences in docs/contracts/E4_CONSUMPTION.md.")
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    parser.add_argument("--out", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()

    blocks = command_blocks(args.doc.read_text(encoding="utf-8"))
    if not blocks:
        raise SystemExit("no bash/sh command fences found")
    results = [(block, run_block(block)) for block in blocks]
    write_results(args.out, results)
    failures = [block.index for block, completed in results if completed.returncode != 0]
    if failures:
        print(f"failed command blocks: {failures}")
        return 1
    print(f"executed {len(results)} command blocks; results={args.out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
