from __future__ import annotations

import json
import os
import re
import shlex
import signal
import subprocess
import uuid
from pathlib import Path
import random
import time
from types import SimpleNamespace
from typing import Any, Callable, Dict, List, Optional, Tuple

from ..core.core import ToolDefinition
from .context import ConductorContext
from ..messaging.markdown_logger import MarkdownLogger
from ..provider import provider_adapter_manager
from ..provider.routing import provider_router
from ..provider.contracts import (
    ProviderMessage,
    ProviderRuntimeContext,
    ProviderRuntimeError,
    ProviderResult,
)
from ..provider.registry import provider_registry
from ..replay import resolve_todo_placeholders
from ..orchestration.coordination import (
    build_completion_signal_proposal,
    build_tool_completion_signal_proposal,
    is_accepted_signal,
    validate_signal_proposal,
)
from ..state.session_state import SessionState
from ..turns import TurnContext
from ..utils.assistant_progress import assistant_is_progress_update
from ..checkpointing.checkpoint_manager import CheckpointManager
from ..hooks.model import HookResult
from .components import latest_real_user_prompt, session_requires_workspace_tool_usage
from .execution_records import (
    ReplayToolOutputMismatchError,
    classify_tool_terminal_state,
    build_tool_execution_outcome_record,
    build_tool_model_render_record,
    legacy_message_view,
)
from .replay_compare import (
    _OPENCODE_ISO_TIMESTAMP_RE,
    _CLAUDE_BUDGET_LINE_RE,
    _replay_tool_output_compare_targets,
    _extract_tool_result_text,
    _normalize_opencode_filetime_timestamps,
    _normalize_claude_system_reminders,
    _normalize_codex_shell_output,
    _normalize_codex_apply_patch_output,
    _normalize_replay_paths,
    record_replay_tool_output_mismatches,
)
from .implementation_receipts import (
    _coerce_subprocess_text,
    _run_subprocess_capture_with_group_timeout,
    _auto_verify_smoke_command_from_prompt,
    _latest_prompt_requests_tool_stop_after_observation,
    _is_allowed_async_result_followup,
    _async_result_task_id_from_activity,
    _async_result_retrieval_tool_for_activity,
    _latest_prompt_requests_read_only_answer_after_observation,
    _observed_tool_calls_since_read_only_prompt,
    _requested_final_answer_terms,
    _is_internal_validation_prompt,
    _required_final_answer_marker,
    _required_final_answer_reminder,
    _strip_internal_prompt_blocks,
    _implementation_write_guard_config,
    _prompt_requires_implementation_write_text,
    _latest_implementation_prompt,
    _implementation_prompt_candidates,
    _latest_prompt_requires_implementation_write,
    _shell_command_is_read_only,
    _command_tunnels_apply_patch,
    _path_is_user_facing_write_target,
    _normalize_write_target,
    _tool_call_write_targets,
    _tool_call_delete_targets,
    _shell_command_delete_targets,
    _latest_prompt_forbidden_direct_commands,
    _latest_prompt_requests_file_deletion,
    _shell_command_write_targets,
    _tool_call_has_user_facing_write_target,
    _write_payload_looks_placeholder,
    _requested_write_targets,
    _successful_patch_result_paths,
    _write_target_matches_requested,
    _requested_write_matches,
    _implementation_task_anchor,
    _missing_requested_write_targets,
    _parsed_call_is_read_only_inspection,
    _implementation_write_receipt_missing,
    _latest_prompt_requests_verification,
    _successful_test_commands,
    _requested_verification_commands_satisfied,
    _implementation_verification_receipt_missing,
    _implementation_receipt_missing,
    _implementation_receipts_satisfied,
    _maybe_auto_verify_make_after_write_receipts,
)
from .completion_guards import (
    _post_receipt_final_reminder,
    _force_post_receipt_final_answer,
    _post_receipt_final_targets,
    _build_post_receipt_final_message,
    _build_read_only_observation_final_message,
    _force_read_only_observation_final_answer,
    _maybe_force_read_only_observation_closure,
    _ensure_tool_completion_final_message,
    _maybe_force_post_write_auto_verification_closure,
    _latest_requested_exact_shell_command,
    _successful_exact_shell_command_observation,
    _maybe_force_requested_shell_command_closure,
    _force_failed_verification_final_answer,
    _failed_requested_write_attempts,
    _force_failed_write_final_answer,
    _reject_completion_without_implementation_write,
    _maybe_block_read_only_implementation_loop,
)
from .tool_executor import (
    _inject_async_result_retrieval,
    _coordination_task_context,
    _record_validated_signal,
    _is_completion_action_result,
    build_exec_func,
    resolve_replay_todo_placeholders,
    _emit_tool_denial_primitives,
    execute_agent_calls,
)
from .turn_runtime import (
    build_turn_context,
    summarize_execution_results,
    emit_turn_snapshot,
    hydrate_turn_context_signals,
    finalize_turn_context_snapshot,
    apply_turn_guards,
    handle_blocked_calls,
    maybe_transition_plan_mode,
)
from .model_output import (
    log_provider_message,
    process_model_output,
    handle_text_tool_calls,
    handle_native_tool_calls,
    retry_with_fallback,
)

__all__ = [
    'Any',
    'Callable',
    'CheckpointManager',
    'ConductorContext',
    'Dict',
    'HookResult',
    'List',
    'MarkdownLogger',
    'Optional',
    'Path',
    'ProviderMessage',
    'ProviderResult',
    'ProviderRuntimeContext',
    'ProviderRuntimeError',
    'ReplayToolOutputMismatchError',
    'SessionState',
    'SimpleNamespace',
    'ToolDefinition',
    'Tuple',
    'TurnContext',
    '_CLAUDE_BUDGET_LINE_RE',
    '_OPENCODE_ISO_TIMESTAMP_RE',
    '_async_result_retrieval_tool_for_activity',
    '_async_result_task_id_from_activity',
    '_auto_verify_smoke_command_from_prompt',
    '_build_post_receipt_final_message',
    '_build_read_only_observation_final_message',
    '_coerce_subprocess_text',
    '_command_tunnels_apply_patch',
    '_coordination_task_context',
    '_emit_tool_denial_primitives',
    '_ensure_tool_completion_final_message',
    '_extract_tool_result_text',
    '_failed_requested_write_attempts',
    '_force_failed_verification_final_answer',
    '_force_failed_write_final_answer',
    '_force_post_receipt_final_answer',
    '_force_read_only_observation_final_answer',
    '_implementation_prompt_candidates',
    '_implementation_receipt_missing',
    '_implementation_receipts_satisfied',
    '_implementation_task_anchor',
    '_implementation_verification_receipt_missing',
    '_implementation_write_guard_config',
    '_implementation_write_receipt_missing',
    '_inject_async_result_retrieval',
    '_is_allowed_async_result_followup',
    '_is_completion_action_result',
    '_is_internal_validation_prompt',
    '_latest_implementation_prompt',
    '_latest_prompt_forbidden_direct_commands',
    '_latest_prompt_requests_file_deletion',
    '_latest_prompt_requests_read_only_answer_after_observation',
    '_latest_prompt_requests_tool_stop_after_observation',
    '_latest_prompt_requests_verification',
    '_latest_prompt_requires_implementation_write',
    '_latest_requested_exact_shell_command',
    '_maybe_auto_verify_make_after_write_receipts',
    '_maybe_block_read_only_implementation_loop',
    '_maybe_force_post_write_auto_verification_closure',
    '_maybe_force_read_only_observation_closure',
    '_maybe_force_requested_shell_command_closure',
    '_missing_requested_write_targets',
    '_normalize_claude_system_reminders',
    '_normalize_codex_apply_patch_output',
    '_normalize_codex_shell_output',
    '_normalize_opencode_filetime_timestamps',
    '_normalize_replay_paths',
    '_normalize_write_target',
    '_observed_tool_calls_since_read_only_prompt',
    '_parsed_call_is_read_only_inspection',
    '_path_is_user_facing_write_target',
    '_post_receipt_final_reminder',
    '_post_receipt_final_targets',
    '_prompt_requires_implementation_write_text',
    '_record_validated_signal',
    '_reject_completion_without_implementation_write',
    '_replay_tool_output_compare_targets',
    '_requested_final_answer_terms',
    '_requested_verification_commands_satisfied',
    '_requested_write_matches',
    '_requested_write_targets',
    '_required_final_answer_marker',
    '_required_final_answer_reminder',
    '_run_subprocess_capture_with_group_timeout',
    '_shell_command_delete_targets',
    '_shell_command_is_read_only',
    '_shell_command_write_targets',
    '_strip_internal_prompt_blocks',
    '_successful_exact_shell_command_observation',
    '_successful_patch_result_paths',
    '_successful_test_commands',
    '_tool_call_delete_targets',
    '_tool_call_has_user_facing_write_target',
    '_tool_call_write_targets',
    '_write_payload_looks_placeholder',
    '_write_target_matches_requested',
    'annotations',
    'apply_turn_guards',
    'assistant_is_progress_update',
    'build_completion_signal_proposal',
    'build_exec_func',
    'build_tool_completion_signal_proposal',
    'build_tool_execution_outcome_record',
    'build_tool_model_render_record',
    'build_turn_context',
    'classify_tool_terminal_state',
    'emit_turn_snapshot',
    'execute_agent_calls',
    'finalize_turn_context_snapshot',
    'handle_blocked_calls',
    'handle_native_tool_calls',
    'handle_text_tool_calls',
    'hydrate_turn_context_signals',
    'is_accepted_signal',
    'json',
    'latest_real_user_prompt',
    'legacy_message_view',
    'log_provider_message',
    'maybe_transition_plan_mode',
    'os',
    'process_model_output',
    'provider_adapter_manager',
    'provider_registry',
    'provider_router',
    'random',
    're',
    'record_replay_tool_output_mismatches',
    'resolve_replay_todo_placeholders',
    'resolve_todo_placeholders',
    'retry_with_fallback',
    'session_requires_workspace_tool_usage',
    'shlex',
    'signal',
    'subprocess',
    'summarize_execution_results',
    'time',
    'uuid',
    'validate_signal_proposal',
]
