import { compile } from "json-schema-to-typescript"
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { basename, dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const REPO_ROOT = join(PACKAGE_ROOT, "..", "..")
const SCHEMA_DIR = join(REPO_ROOT, "contracts", "kernel", "schemas")
const GENERATED_ROOT = join(PACKAGE_ROOT, "src", "generated")
const TYPES_DIR = join(GENERATED_ROOT, "types")
const PACKS_MANIFEST = join(REPO_ROOT, "contracts", "kernel", "packs.v1.json")
const SCHEMA_README = join(SCHEMA_DIR, "README.md")
const CONTRACT_TIER_REGISTRY = join(REPO_ROOT, "contracts", "kernel", "registries", "contract_tiers.v1.json")
const PHASE20_UNPACKED_SCHEMAS: Record<string, true> = {
  "bb.contract_tiers.v1.schema.json": true,
  "bb.e4.lane_lock.v1.schema.json": true,
  "bb.e4.lane_manifest.v1.schema.json": true,
}

interface SchemaEntry {
  filename: string
  schemaId: string
  typeName: string
  schema: Record<string, unknown>
}

interface PackEntry {
  id: string
  status: string
  description: string
  schemaFilenames: string[]
}

interface SchemaPackEntry {
  id?: unknown
  status?: unknown
  description?: unknown
  metadata?: {
    schemas?: unknown
  }
}

interface ContractTierEntry {
  schema_id?: unknown
  tier?: unknown
}

function pascalCase(value: string): string {
  return value
    .replace(/^bb\./, "")
    .replace(/\.schema\.json$/, "")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

function readSchemas(): SchemaEntry[] {
  return readdirSync(SCHEMA_DIR)
    .filter((filename) => filename.endsWith(".schema.json"))
    .sort((a, b) => a.localeCompare(b))
    .map((filename) => {
      const schema = JSON.parse(readFileSync(join(SCHEMA_DIR, filename), "utf8")) as Record<string, unknown>
      const schemaId = typeof schema.$id === "string" ? schema.$id : filename
      return { filename, schemaId, typeName: pascalCase(filename), schema }
    })
}

function generatedHeader(sourceRel: string): string {
  return `// Generated by scripts/generate.ts from ${sourceRel}. Do not edit by hand.\n\n`
}

async function emitTypes(entries: SchemaEntry[]): Promise<void> {
  for (const entry of entries) {
    const sourcePath = join(SCHEMA_DIR, entry.filename)
    const output = await compile({ ...entry.schema, title: entry.typeName }, entry.typeName, {
      cwd: SCHEMA_DIR,
      bannerComment: "",
      declareExternallyReferenced: true,
      enableConstEnums: false,
      unreachableDefinitions: true,
    })
    const outFile = join(TYPES_DIR, entry.filename.replace(/\.schema\.json$/, ".ts"))
    writeFileSync(outFile, generatedHeader(relative(PACKAGE_ROOT, sourcePath)) + output.trimEnd() + "\n", "utf8")
  }
}

function readPacks(entries: SchemaEntry[]): PackEntry[] {
  const manifest = JSON.parse(readFileSync(PACKS_MANIFEST, "utf8")) as { entries?: SchemaPackEntry[] }
  const schemaFilenames = new Set(entries.map((entry) => entry.filename))
  const assigned = new Map<string, string>()
  const packs: PackEntry[] = []

  for (const rawEntry of manifest.entries ?? []) {
    if (typeof rawEntry.id !== "string" || rawEntry.id.length === 0) {
      throw new Error("contracts/kernel/packs.v1.json contains a pack without a string id")
    }
    if (typeof rawEntry.status !== "string" || rawEntry.status.length === 0) {
      throw new Error(`contracts/kernel/packs.v1.json pack ${rawEntry.id} is missing status`)
    }
    const rawSchemas = rawEntry.metadata?.schemas
    if (!Array.isArray(rawSchemas) || rawSchemas.some((schema) => typeof schema !== "string")) {
      throw new Error(`contracts/kernel/packs.v1.json pack ${rawEntry.id} must declare metadata.schemas[]`)
    }
    const schemaNames = [...rawSchemas].sort((a, b) => a.localeCompare(b)) as string[]
    for (const schemaName of schemaNames) {
      if (!schemaFilenames.has(schemaName)) {
        throw new Error(`contracts/kernel/packs.v1.json pack ${rawEntry.id} references missing schema ${schemaName}`)
      }
      const existingPack = assigned.get(schemaName)
      if (existingPack !== undefined) {
        throw new Error(`contracts/kernel/packs.v1.json assigns ${schemaName} to both ${existingPack} and ${rawEntry.id}`)
      }
      assigned.set(schemaName, rawEntry.id)
    }
    packs.push({
      id: rawEntry.id,
      status: rawEntry.status,
      description: typeof rawEntry.description === "string" ? rawEntry.description : "",
      schemaFilenames: schemaNames,
    })
  }

  const missing = [...schemaFilenames]
    .filter((filename) => !assigned.has(filename) && PHASE20_UNPACKED_SCHEMAS[filename] !== true)
    .sort((a, b) => a.localeCompare(b))
  if (missing.length > 0) {
    throw new Error(`contracts/kernel/packs.v1.json does not assign schemas: ${missing.join(", ")}`)
  }

  return packs
}


function readContractTiers(entries: SchemaEntry[]): Map<string, string> {
  const registry = JSON.parse(readFileSync(CONTRACT_TIER_REGISTRY, "utf8")) as { entries?: ContractTierEntry[] }
  const tiers = new Map<string, string>()
  for (const rawEntry of registry.entries ?? []) {
    if (typeof rawEntry.schema_id !== "string" || typeof rawEntry.tier !== "string") {
      throw new Error("contract_tiers.v1.json entries must declare string schema_id and tier values")
    }
    if (tiers.has(rawEntry.schema_id)) {
      throw new Error(`contract_tiers.v1.json contains duplicate schema ${rawEntry.schema_id}`)
    }
    tiers.set(rawEntry.schema_id, rawEntry.tier)
  }
  const schemaIds = new Set(entries.map((entry) => basename(entry.filename, ".schema.json")))
  const missing = [...schemaIds].filter((schemaId) => !tiers.has(schemaId)).sort((a, b) => a.localeCompare(b))
  const stale = [...tiers.keys()].filter((schemaId) => !schemaIds.has(schemaId)).sort((a, b) => a.localeCompare(b))
  if (missing.length > 0 || stale.length > 0) {
    throw new Error(
      `contract_tiers.v1.json must match generated schemas exactly; missing: ${missing.join(", ") || "none"}; stale: ${stale.join(", ") || "none"}`,
    )
  }
  return tiers
}

function schemaIdsForPack(pack: PackEntry, entriesByFilename: Map<string, SchemaEntry>): string[] {
  return pack.schemaFilenames.map((filename) => {
    const entry = entriesByFilename.get(filename)
    if (entry === undefined) {
      throw new Error(`Pack ${pack.id} references missing generated schema ${filename}`)
    }
    return entry.schemaId
  })
}

function emitRegistry(entries: SchemaEntry[]): void {
  const schemaObjects = entries
    .map((entry) => `  ${JSON.stringify(entry.schemaId)}: ${JSON.stringify(entry.schema, null, 2).replace(/^/gm, "  ").trimStart()}`)
    .join(",\n")
  const schemaAliases = entries
    .map((entry) => {
      const aliases = [entry.filename].filter((alias) => alias !== entry.schemaId)
      return `  ${JSON.stringify(entry.schemaId)}: ${JSON.stringify(aliases)}`
    })
    .join(",\n")

  const registry = `${generatedHeader(relative(PACKAGE_ROOT, SCHEMA_DIR))}import * as Ajv2020Module from "ajv/dist/2020.js"
import type { ValidateFunction } from "ajv"

const Ajv2020Candidate: unknown =
  Ajv2020Module && typeof Ajv2020Module === "object" && "default" in Ajv2020Module ? Ajv2020Module.default : Ajv2020Module
const Ajv2020 = Ajv2020Candidate as new (opts?: { allErrors?: boolean; validateFormats?: boolean }) => any
const ajv = new Ajv2020({ allErrors: true, validateFormats: false })

export const GENERATED_SCHEMA_OBJECTS = {
${schemaObjects}
} as const satisfies Record<string, object>

const GENERATED_SCHEMA_ALIASES: Record<string, readonly string[]> = {
${schemaAliases}
}

export const GENERATED_SCHEMAS: Record<string, { schema: object; validate: ValidateFunction }> = {}

for (const [schemaId, schema] of Object.entries(GENERATED_SCHEMA_OBJECTS)) {
  ajv.addSchema(schema, schemaId)
  for (const alias of GENERATED_SCHEMA_ALIASES[schemaId] ?? []) {
    ajv.addSchema(schema, alias)
  }
}

for (const [schemaId, schema] of Object.entries(GENERATED_SCHEMA_OBJECTS)) {
  const validate = ajv.getSchema(schemaId) ?? ajv.compile(schema)
  GENERATED_SCHEMAS[schemaId] = { schema, validate }
}
`
  writeFileSync(join(GENERATED_ROOT, "registry.ts"), registry, "utf8")
}

function emitIndex(entries: SchemaEntry[], packs: PackEntry[]): void {
  const entriesByFilename = new Map(entries.map((entry) => [entry.filename, entry]))
  const typeExports = entries
    .map((entry) => `export type { ${entry.typeName} } from "./types/${entry.filename.replace(/\.schema\.json$/, ".js")}"`)
    .join("\n")
  const packObjects = packs
    .map((pack) => {
      const schemaIds = schemaIdsForPack(pack, entriesByFilename)
      return `  ${JSON.stringify(pack.id)}: {
    id: ${JSON.stringify(pack.id)},
    status: ${JSON.stringify(pack.status)},
    description: ${JSON.stringify(pack.description)},
    schemas: ${JSON.stringify(schemaIds, null, 2).replace(/^/gm, "    ").trimStart()}
  }`
    })
    .join(",\n")
  const packSchemaIndexes = packs
    .map((pack) => `  ${JSON.stringify(pack.id)}: PACKS[${JSON.stringify(pack.id)}].schemas`)
    .join(",\n")
  const packRegistryIndexes = packs
    .map((pack) => {
      const schemaIds = schemaIdsForPack(pack, entriesByFilename)
      const schemas = schemaIds.map((schemaId) => `    ${JSON.stringify(schemaId)}: GENERATED_SCHEMAS[${JSON.stringify(schemaId)}]`).join(",\n")
      return `  ${JSON.stringify(pack.id)}: {
${schemas}
  }`
    })
    .join(",\n")
  writeFileSync(
    join(GENERATED_ROOT, "index.ts"),
    `${generatedHeader("contracts/kernel/schemas/*.schema.json and contracts/kernel/packs.v1.json")}import { GENERATED_SCHEMAS, GENERATED_SCHEMA_OBJECTS } from "./registry.js"

export { GENERATED_SCHEMAS, GENERATED_SCHEMA_OBJECTS }

export const PACKS = {
${packObjects}
} as const satisfies Record<string, { id: string; status: string; description: string; schemas: readonly string[] }>

export const GENERATED_SCHEMA_IDS_BY_PACK = {
${packSchemaIndexes}
} as const satisfies Record<string, readonly string[]>

export const GENERATED_SCHEMAS_BY_PACK = {
${packRegistryIndexes}
} as const

${typeExports}
`,
    "utf8",
  )
}

function emitSchemaReadme(entries: SchemaEntry[], packs: PackEntry[], tiers: Map<string, string>): void {
  const entriesByFilename = new Map(entries.map((entry) => [entry.filename, entry]))
  const lines = [
    "# Kernel Schema Pack",
    "",
    "This directory contains machine-readable schemas for the shared BreadBoard kernel contract program.",
    "",
    "Schemas are grouped by `contracts/kernel/packs.v1.json`; the three Phase 20 governance schemas remain registry-only so pack membership does not change.",
    "",
    "A schema appearing here means:",
    "",
    "- it belongs to the shared kernel contract program",
    "- its shape is stable enough to start validating against",
    "- its semantics should also have a paired human-readable dossier under `docs/contracts/kernel/semantics/`",
    "",
    "A schema appearing here does **not** mean every detail of the associated semantics is complete.",
    "",
    "Tiers are generated from `contracts/kernel/registries/contract_tiers.v1.json`. “Minimal” refers only to the `runtime_protocol` tier.",
    "",
    "## Packs",
  ]

  const appendTableRow = (entry: SchemaEntry): void => {
    const schemaId = basename(entry.filename, ".schema.json")
    const label = typeof entry.schema.title === "string" ? entry.schema.title : entry.schemaId.split("/").at(-1)
    const tier = tiers.get(schemaId)
    if (tier === undefined) {
      throw new Error(`contract_tiers.v1.json is missing ${schemaId}`)
    }
    lines.push(`| \`${schemaId}\` | ${label} | \`${tier}\` |`)
  }

  for (const pack of packs) {
    lines.push(
      "",
      `### ${pack.id}`,
      "",
      pack.description,
      "",
      `Status: \`${pack.status}\``,
      "",
      "| Schema | Title | Tier |",
      "| --- | --- | --- |",
    )
    for (const filename of pack.schemaFilenames) {
      const entry = entriesByFilename.get(filename)
      if (entry === undefined) {
        throw new Error(`Pack ${pack.id} references missing generated schema ${filename}`)
      }
      appendTableRow(entry)
    }
  }

  lines.push(
    "",
    "### phase20_registry",
    "",
    "Phase 20 governance schemas are classified without changing pack membership.",
    "",
    "Status: `active`",
    "",
    "| Schema | Title | Tier |",
    "| --- | --- | --- |",
  )
  for (const filename of Object.keys(PHASE20_UNPACKED_SCHEMAS).sort((a, b) => a.localeCompare(b))) {
    const entry = entriesByFilename.get(filename)
    if (entry === undefined) {
      throw new Error(`Missing Phase 20 schema ${filename}`)
    }
    appendTableRow(entry)
  }

  writeFileSync(SCHEMA_README, `${lines.join("\n")}\n`, "utf8")
}

async function main(): Promise<void> {
  const entries = readSchemas()
  const packs = readPacks(entries)
  const tiers = readContractTiers(entries)
  rmSync(GENERATED_ROOT, { recursive: true, force: true })
  mkdirSync(TYPES_DIR, { recursive: true })
  await emitTypes(entries)
  emitRegistry(entries)
  emitIndex(entries, packs)
  emitSchemaReadme(entries, packs, tiers)
  console.log(JSON.stringify({ generatedSchemas: entries.length, generatedPacks: packs.length, outputDir: relative(PACKAGE_ROOT, GENERATED_ROOT) }))
}

await main()
