import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

interface OpenApiDocument {
  readonly openapi: string
  readonly paths: Record<string, Record<string, OpenApiOperation>>
  readonly components?: { readonly schemas?: Record<string, unknown> }
}

interface OpenApiOperation {
  readonly operationId?: string
  readonly requestBody?: unknown
  readonly responses?: Record<string, unknown>
}

interface ClientRoute {
  readonly method: "GET" | "POST" | "DELETE"
  readonly path: string
}

const scriptDir = dirname(fileURLToPath(import.meta.url))
const tuiRoot = resolve(scriptDir, "..")
const repoRoot = resolve(tuiRoot, "..")
const openApiPath = resolve(repoRoot, "docs/contracts/cli_bridge/openapi.json")
const clientPath = resolve(tuiRoot, "src/api/client.ts")
const generatedDir = resolve(tuiRoot, "src/api/generated")
const routeManifestPath = resolve(generatedDir, "client-route-manifest.json")
const openApiTypesPath = resolve(generatedDir, "openapi-types.ts")
const checkMode = process.argv.includes("--check")

const generatedHeader = (source: string): string => `// Generated by scripts/generate_api_client.ts from ${source}. Do not edit by hand.\n\n`

const normalizeTemplatePath = (path: string): string => path.replace(/\$\{[^}]+\}/g, "{}")
const normalizeOpenApiPath = (path: string): string => path.replace(/\{[^}]+\}/g, "{}")

const extractClientRoutes = (source: string): ClientRoute[] => {
  const routes = new Map<string, ClientRoute>()
  const callPattern = /requestWithConfig<[^>]+>\(config,\s*([`"])([\s\S]*?)\1,\s*"(GET|POST|DELETE)"/g
  for (const match of source.matchAll(callPattern)) {
    const method = match[3] as ClientRoute["method"]
    const path = normalizeTemplatePath(match[2])
    routes.set(`${method} ${path}`, { method, path })
  }
  return [...routes.values()].sort((left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method))
}

const extensionClientRoutes: Record<string, true> = {
  "GET /sessions/{}/ctrees/tree": true,
  "GET /sessions/{}/ctrees/disk": true,
  "GET /sessions/{}/ctrees/events": true,
  "GET /v1/status": true,
  "POST /v1/rl/runs": true,
  "GET /v1/rl/runs/{}": true,
  "GET /v1/rl/runs/{}/artifacts": true,
  "GET /v1/rl/runs/{}/audit": true,
  "POST /v1/rl/runs/{}/cancel": true,
  "GET /v1/rl/runs/{}/events": true,
  "GET /v1/rl/runs/{}/replay/{}": true,
  "GET /v1/sessions/{}/records": true,
}

const assertRoutesHaveOpenApiOwners = (routes: readonly ClientRoute[], openapi: OpenApiDocument): void => {
  const openApiRoutes = new Set<string>()
  for (const [path, operations] of Object.entries(openapi.paths)) {
    for (const method of Object.keys(operations)) {
      openApiRoutes.add(`${method.toUpperCase()} ${normalizeOpenApiPath(path)}`)
    }
  }
  const missing = routes
    .map((route) => `${route.method} ${route.path}`)
    .filter((route) => !openApiRoutes.has(route) && !extensionClientRoutes[route])
  if (missing.length > 0) {
    throw new Error(`Client routes missing from OpenAPI contract: ${missing.join(", ")}`)
  }
}

const assertNoLegacyRlClientRoutes = (routes: readonly ClientRoute[]): void => {
  const legacyRlRoutes = routes.filter((route) => route.path.startsWith("/rl/"))
  if (legacyRlRoutes.length > 0) {
    throw new Error(`Legacy /rl client routes remain: ${legacyRlRoutes.map((route) => `${route.method} ${route.path}`).join(", ")}`)
  }
}

const jsonLiteral = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

const schemaTypeName = (name: string): string => name.replace(/[^A-Za-z0-9_$]/g, "_")

const schemaToType = (schema: unknown): string => {
  if (schema === true) return "unknown"
  if (schema === false) return "never"
  if (schema === null || typeof schema !== "object") return "unknown"
  const value = schema as Record<string, unknown>
  if (typeof value.$ref === "string") return schemaTypeName(value.$ref.split("/").at(-1) ?? "unknown")
  if (Array.isArray(value.anyOf)) return value.anyOf.map(schemaToType).join(" | ")
  if (Array.isArray(value.oneOf)) return value.oneOf.map(schemaToType).join(" | ")
  if (Array.isArray(value.enum)) return value.enum.map((item) => JSON.stringify(item)).join(" | ")
  const type = value.type
  if (Array.isArray(type)) return type.map((entry) => schemaToType({ ...value, type: entry })).join(" | ")
  if (type === "null") return "null"
  if (type === "string") return "string"
  if (type === "integer" || type === "number") return "number"
  if (type === "boolean") return "boolean"
  if (type === "array") return `ReadonlyArray<${schemaToType(value.items ?? true)}>`
  if (type === "object" || value.properties) {
    const properties = (value.properties && typeof value.properties === "object" ? value.properties : {}) as Record<string, unknown>
    const required = new Set(Array.isArray(value.required) ? value.required.filter((item): item is string => typeof item === "string") : [])
    const lines = Object.entries(properties).map(([key, child]) => `  readonly ${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${schemaToType(child)}`)
    if (value.additionalProperties === true) lines.push("  readonly [key: string]: unknown")
    return lines.length > 0 ? `{\n${lines.join("\n")}\n}` : "Record<string, unknown>"
  }
  return "unknown"
}

const emitOpenApiTypes = (openapi: OpenApiDocument): string => {
  const schemas = openapi.components?.schemas ?? {}
  const schemaTypes = Object.entries(schemas)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, schema]) => `export type ${schemaTypeName(name)} = ${schemaToType(schema)}\n`)
    .join("\n")
  return `${generatedHeader("docs/contracts/cli_bridge/openapi.json")}export const OPENAPI_VERSION = ${JSON.stringify(openapi.openapi)} as const\n\n${schemaTypes}`
}

const emitRouteManifest = (routes: readonly ClientRoute[]): string => jsonLiteral({
  schema_version: "bb.tui_api_client_routes.v1",
  generated_from: "docs/contracts/cli_bridge/openapi.json + src/api/client.ts wrapper surface",
  routes,
})

const maybeWrite = async (path: string, content: string): Promise<void> => {
  if (checkMode) {
    const current = await readFile(path, "utf8")
    if (current !== content) {
      throw new Error(`${path} is stale; run npm run generate:api-client`)
    }
    return
  }
  await writeFile(path, content, "utf8")
}

const openapi = JSON.parse(await readFile(openApiPath, "utf8")) as OpenApiDocument
const clientSource = await readFile(clientPath, "utf8")
const routes = extractClientRoutes(clientSource)
assertNoLegacyRlClientRoutes(routes)
assertRoutesHaveOpenApiOwners(routes, openapi)
await mkdir(generatedDir, { recursive: true })
await maybeWrite(routeManifestPath, emitRouteManifest(routes))
await maybeWrite(openApiTypesPath, emitOpenApiTypes(openapi))
console.log(`API client generated artifacts ${checkMode ? "verified" : "written"} (${routes.length} routes, ${Object.keys(openapi.components?.schemas ?? {}).length} schemas).`)
