"""Public authoring contract for supervised BreadBoard policy modules.

The package root intentionally exports only standard-library contract records and
framing helpers.  Provider codecs live in :mod:`breadboard.modules.provider` so
importing ordinary author code cannot pull provider clients into a worker.
"""
from .author import (
    AttemptId,
    CheckpointCapture,
    CheckpointCompatibility,
    CheckpointCompatibilityContext,
    CheckpointEnvelope,
    CheckpointProposal,
    CheckpointRefusal,
    CheckpointRequest,
    ChildFailed,
    ChildHandle,
    ChildOutput,
    ChildOutcome,
    ChildPlan,
    ChildSucceeded,
    ChildTarget,
    ChildUnknown,
    ChildWorkAccess,
    CompactionProposal,
    ContinueResult,
    ContextSnapshot,
    ContextSourceProvenance,
    DependencyAccess,
    DependencyBindings,
    DependencyDeclaration,
    EffectiveContextDocument,
    FailureResult,
    GenerationId,
    InputEnvelope,
    InstanceId,
    InstanceIdentity,
    JsonValue,
    MAX_CHECKPOINT_BYTES,
    MAX_FRAME_BYTES,
    ModuleId,
    ModuleInput,
    OutputEnvelope,
    OutputResult,
    OutputSequence,
    PolicyFailure,
    PolicyInstance,
    PolicyModule,
    ProviderAccess,
    RequestId,
    ToolAccess,
    ToolApproval,
    ToolApprovalRequest,
    ToolCancelled,

    ToolFailed,
    ToolOutcome,
    ToolSucceeded,
    ToolUnknown,
    TurnContextAccess,
    TurnPolicyDecision,
    TurnPolicyReceipt,
    WorkId,
    WorkerSessionId,
)
from .authority import (
    AdmissionGrant,
    AuthorityDeclaration,
    ChildAuthority,
    CredentialDisclosure,
    NetworkAuthority,
    NetworkOperation,
    ProjectAuthority,
    ProjectOperation,
)
from .transport import (
    FrameEOF,
    FrameLimitError,
    PROTOCOL_VERSION,
    RequestKey,
    TransportError,
    WIRE_KINDS,
    WireHeader,
    WireKind,
    WireMessage,
    WireProtocolError,
    decode_bytes,
    encode_bytes,
    read_frame,
    read_message,
    write_frame,
    write_message,
)

from .runtime import oci_worker_runtime

__all__ = [
    "AdmissionGrant", "AuthorityDeclaration", "ChildAuthority",
    "CredentialDisclosure", "NetworkAuthority", "NetworkOperation",
    "ProjectAuthority", "ProjectOperation",
    "AttemptId", "CheckpointCapture", "CheckpointCompatibility",
    "CheckpointCompatibilityContext", "CheckpointEnvelope", "CheckpointProposal",
    "CheckpointRefusal", "CheckpointRequest", "ChildFailed", "ChildHandle",
    "ChildOutput", "ChildOutcome", "ChildPlan", "ChildSucceeded", "ChildTarget",
    "ChildUnknown", "ChildWorkAccess", "CompactionProposal", "ContinueResult",
    "ContextSnapshot", "ContextSourceProvenance", "DependencyAccess",
    "DependencyBindings", "DependencyDeclaration",
    "EffectiveContextDocument", "FailureResult", "FrameEOF", "FrameLimitError",
    "GenerationId", "InputEnvelope", "InstanceId", "InstanceIdentity", "JsonValue",
    "MAX_CHECKPOINT_BYTES", "MAX_FRAME_BYTES", "ModuleId", "ModuleInput",
    "OutputEnvelope", "OutputResult", "OutputSequence", "PolicyFailure",
    "PolicyInstance", "PolicyModule", "PROTOCOL_VERSION", "ProviderAccess",
    "RequestId", "RequestKey", "ToolAccess", "ToolApproval", "ToolApprovalRequest",
    "ToolCancelled", "ToolFailed", "ToolOutcome", "ToolSucceeded", "ToolUnknown",
    "TransportError", "TurnContextAccess", "TurnPolicyDecision", "TurnPolicyReceipt",
    "WIRE_KINDS", "WireHeader", "WireKind", "WireMessage",
    "WireProtocolError", "WorkId", "WorkerSessionId", "decode_bytes", "encode_bytes",
    "oci_worker_runtime", "read_frame", "read_message", "write_frame", "write_message",
]
