import type { ResolvedTuiConfig, TuiConfigInput, TuiPresetId } from "./types.js"

export const BUILTIN_TUI_PRESETS: Record<TuiPresetId, TuiConfigInput> = {
  breadboard_default: {
    landing: {
      variant: "auto",
      borderStyle: "round",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "❯",
      placeholderClassic: "Type your request…",
      placeholderClaude: 'Try "refactor <filepath>"',
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: true,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "· Deciphering… (esc to interrupt · thinking)",
      completionTemplate: "✻ Cooked for {duration}",
    },
  },
  claude_code_like: {
    landing: {
      variant: "board",
      borderStyle: "round",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "❯",
      placeholderClassic: "Type your request…",
      placeholderClaude: 'Try "fix typecheck errors"',
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: true,
      todoPreviewAboveInput: true,
      todoPreviewMaxItems: 7,
      todoPreviewSelection: "active_first",
      todoPreviewShowHiddenCount: true,
      todoPreviewStyle: "nice",
      todoPreviewMinRowsToShow: 10,
      todoPreviewSmallRowsMaxItems: 3,
      todoAutoFollowScope: "on",
      todoAutoFollowHysteresisMs: 1200,
      todoAutoFollowManualOverrideMs: 15000,
    },
    statusLine: {
      position: "below_input",
      align: "right",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "· Deciphering… (esc to interrupt · thinking)",
      completionTemplate: "✻ Cooked for {duration}",
    },
  },
  codex_cli_like: {
    landing: {
      variant: "compact",
      borderStyle: "single",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "›",
      placeholderClassic: "Write tests for @filename",
      placeholderClaude: "Find and fix a bug in @filename",
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: false,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "• Working (esc to interrupt)",
      completionTemplate: "• Worked for {duration}",
    },
  },
  claude_like_subagents: {
    landing: {
      variant: "board",
      borderStyle: "round",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "❯",
      placeholderClassic: "Describe the task for background agents",
      placeholderClaude: 'Try "delegate test matrix and summarize"',
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: true,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "· Coordinating subagents… (esc to interrupt)",
      completionTemplate: "✻ Subagent run complete in {duration}",
    },
    subagents: {
      enabled: true,
      stripEnabled: true,
      toastsEnabled: true,
      taskboardEnabled: true,
      focusEnabled: true,
      focusMode: "lane",
      coalesceMs: 100,
      maxWorkItems: 300,
      maxStepsPerTask: 80,
    },
  },
  opencode_like_subagents: {
    landing: {
      variant: "compact",
      borderStyle: "single",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: ">",
      placeholderClassic: "Queue background work and inspect lanes",
      placeholderClaude: 'Try "run async checks and show focus lane"',
      ruleCharacter: "-",
      showTopRule: true,
      showBottomRule: false,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: ". Running subagent lanes (esc to interrupt)",
      completionTemplate: ". Background run finished in {duration}",
    },
    subagents: {
      enabled: true,
      stripEnabled: true,
      toastsEnabled: true,
      taskboardEnabled: true,
      focusEnabled: true,
      focusMode: "lane",
      coalesceMs: 120,
      maxWorkItems: 250,
      maxStepsPerTask: 64,
    },
  },
  claude_like_subagents_swap: {
    landing: {
      variant: "board",
      borderStyle: "round",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "❯",
      placeholderClassic: "Describe the task for background agents",
      placeholderClaude: 'Try "delegate test matrix and swap focus lane"',
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: true,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "· Coordinating subagents… (swap mode · esc to interrupt)",
      completionTemplate: "✻ Subagent run complete in {duration}",
    },
    subagents: {
      enabled: true,
      stripEnabled: true,
      toastsEnabled: true,
      taskboardEnabled: true,
      focusEnabled: true,
      focusMode: "swap",
      coalesceMs: 110,
      maxWorkItems: 320,
      maxStepsPerTask: 90,
    },
  },
  codex_like_subagents_dense: {
    landing: {
      variant: "compact",
      borderStyle: "single",
      showAsciiArt: true,
    },
    composer: {
      promptPrefix: "›",
      placeholderClassic: "Queue dense background work and inspect lanes",
      placeholderClaude: 'Try "run parallel checks and inspect dense taskboard"',
      ruleCharacter: "─",
      showTopRule: true,
      showBottomRule: false,
    },
    statusLine: {
      position: "above_input",
      align: "left",
      showWhenPending: true,
      showOnComplete: true,
      activeText: "• Running dense subagent lanes (esc to interrupt)",
      completionTemplate: "• Dense run finished in {duration}",
    },
    subagents: {
      enabled: true,
      stripEnabled: true,
      toastsEnabled: true,
      taskboardEnabled: true,
      focusEnabled: true,
      focusMode: "lane",
      coalesceMs: 90,
      maxWorkItems: 360,
      maxStepsPerTask: 120,
    },
  },
}

export const DEFAULT_TUI_PRESET: TuiPresetId = "breadboard_default"

export const DEFAULT_RESOLVED_TUI_CONFIG: ResolvedTuiConfig = {
  preset: DEFAULT_TUI_PRESET,
  display: {
    asciiOnly: false,
    colorMode: "truecolor",
  },
  landing: {
    variant: "auto",
    borderStyle: "round",
    showAsciiArt: true,
  },
  composer: {
    promptPrefix: "❯",
    placeholderClassic: "Type your request…",
    placeholderClaude: 'Try "refactor <filepath>"',
    ruleCharacter: "─",
    showTopRule: true,
    showBottomRule: true,
    todoPreviewAboveInput: false,
    todoPreviewMaxItems: 7,
    todoPreviewSelection: "first_n",
    todoPreviewShowHiddenCount: false,
    todoPreviewStyle: "minimal",
    todoPreviewMinRowsToShow: 10,
    todoPreviewSmallRowsMaxItems: 3,
    todoAutoFollowScope: "off",
    todoAutoFollowHysteresisMs: 1200,
    todoAutoFollowManualOverrideMs: 15000,
  },
  statusLine: {
    position: "above_input",
    align: "left",
    showWhenPending: true,
    showOnComplete: true,
    activeText: "· Deciphering… (esc to interrupt · thinking)",
    completionTemplate: "✻ Cooked for {duration}",
  },
  markdown: {
    shikiTheme: "andromeeda",
  },
  diff: {
    previewMaxLines: 24,
    maxTokenizedLines: 400,
    colors: {
      addLineBg: "#123225",
      deleteLineBg: "#3a1426",
      hunkLineBg: "#2c2436",
      addInlineBg: "#1a4d33",
      deleteInlineBg: "#6d1c3a",
      addText: "#2dbd8d",
      deleteText: "#ff5f79",
      hunkText: "#B36BFF",
      metaText: "#7CF2FF",
    },
  },
  subagents: {
    enabled: false,
    stripEnabled: false,
    toastsEnabled: false,
    taskboardEnabled: false,
    focusEnabled: false,
    focusMode: "lane",
    coalesceMs: 125,
    maxWorkItems: 200,
    maxStepsPerTask: 50,
  },
  meta: {
    strict: false,
    warnings: [],
    sources: ["defaults"],
  },
}

export const isBuiltinPreset = (value: string): value is TuiPresetId =>
  value === "breadboard_default" ||
  value === "claude_code_like" ||
  value === "codex_cli_like" ||
  value === "claude_like_subagents" ||
  value === "opencode_like_subagents" ||
  value === "claude_like_subagents_swap" ||
  value === "codex_like_subagents_dense"
