#!/usr/bin/env python3
"""Engine-rename occurrence audit (EXECUTION_MASTER_V1 R-0A).

Scans every git-tracked file (text bodies plus ZIP/WHEEL/TAR/GZIP members and
.patch files) for references to the legacy engine package name and emits a
classified occurrence manifest with per-file SHA-256 and parent traces for the
frozen artifacts named by the plan.

The audit exits nonzero if any occurrence cannot be classified, so the rename
codemod may only consume manifests this tool has accepted.

The legacy package needle is assembled at runtime so this file never contains
a literal occurrence of the name it audits.
"""
from __future__ import annotations

import argparse
import fnmatch
import gzip
import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

NEEDLE = "agentic_coder" + "_prototype"

DISPOSITIONS = (
    "live-rewrite",
    "preserve-byte",
    "compat-resolve",
    "archive-member",
    "generated-regen",
)

# First-match-wins path rules (fnmatch globs against repo-relative posix paths).
# The trailing catch-all may be disabled (--no-catch-all) to prove the
# unclassified guard; production runs keep it.
PATH_RULES: list[tuple[str, str]] = [
    # Frozen P3 compiler configs (plan R-0B1: preserve-byte, resolved at runtime).
    ("agent_configs/misc/oh_my_pi_p3_*.yaml", "preserve-byte"),
    # Frozen evidence and accepted history: never rewritten.
    ("docs/conformance/evidence_snapshots/*", "preserve-byte"),
    ("docs_tmp/*", "preserve-byte"),
    ("*.patch", "preserve-byte"),
    ("*.diff", "preserve-byte"),
    ("*frozen_public_surface.v1.json", "preserve-byte"),
    ("*e4_immutable_inputs.v1.zip", "preserve-byte"),
    # Pinned artifacts (R-0B5/R-0B8 fixtures assert byte-identity forever).
    ("config/e4_lanes/evidence_inputs/e4_immutable_inputs.v1.manifest.json", "preserve-byte"),
    ("docs/plans/phase_20_right_shape/SCOUT_FACTS.json", "preserve-byte"),
    # Historical fixtures loaded through the legacy resolver at runtime.
    ("tests/fixtures/*", "compat-resolve"),
    # Rename machinery itself: legacy-name literals are load-bearing (epoch
    # tables, matrix fixtures, codemod defaults) and resolve via the alias
    # layer - never blind-rewritten.
    ("agentic_coder_prototype/compat/legacy_names.py", "compat-resolve"),
    ("agentic_coder_prototype/compat/alias_import.py", "compat-resolve"),
    ("breadboard_engine/compat/legacy_names.py", "compat-resolve"),
    ("breadboard_engine/compat/alias_import.py", "compat-resolve"),
    ("tests/rename_compat/*", "compat-resolve"),
    ("scripts/dev/rename_codemod.py", "compat-resolve"),
    ("scripts/dev/make_rename_compat_fixtures.py", "compat-resolve"),
    ("scripts/dev/audit_engine_rename.py", "compat-resolve"),
    ("scripts/dev/shim_package_init.template.py", "compat-resolve"),
    # Generated outputs: regenerated by their generators after the rename.
    ("*/dist/*", "generated-regen"),
    ("artifacts/*", "generated-regen"),
    ("*.egg-info/*", "generated-regen"),
]
CATCH_ALL = ("*", "live-rewrite")

ARCHIVE_SUFFIXES = (".zip", ".whl", ".tar", ".tar.gz", ".tgz", ".gz")

# Plan R-0A5 parent-trace targets (globs; every existing match is recorded).
PARENT_TRACE_GLOBS = [
    "agent_configs/misc/oh_my_pi_p3_*.yaml",
    "agent_configs/e4_lanes/*.yaml",
    "config/e4_lanes/*",
    "docs/conformance/evidence_snapshots/phase16_er_progress/*p6_6*",
    "config/e4_lanes/evidence_inputs/oh_my_pi_p6_6_*.json",
    "*frozen_public_surface.v1.json",
    "contracts/kernel/registries/*.json",
    "*e4_immutable_inputs.v1.zip",
    "tests/fixtures/ctrees/*",
    "tests/Fixtures/compat/*",
]


def sha256_path(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def classify(relpath: str, rules) -> str | None:
    for pattern, disposition in rules:
        if fnmatch.fnmatch(relpath, pattern):
            return disposition
    return None


def kind_for(relpath: str) -> str:
    suffix = Path(relpath).suffix.lower()
    return {
        ".py": "python-source",
        ".pyi": "python-source",
        ".yaml": "yaml-config",
        ".yml": "yaml-config",
        ".json": "json-config",
        ".md": "doc",
        ".rst": "doc",
        ".txt": "doc",
        ".sh": "script",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".patch": "patch",
        ".diff": "patch",
        ".toml": "toml-config",
        ".cfg": "ini-config",
        ".ini": "ini-config",
    }.get(suffix, "other")


def iter_text_occurrences(data: bytes):
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return
    for lineno, line in enumerate(text.splitlines(), 1):
        count = line.count(NEEDLE)
        if count:
            yield lineno, count


def scan_archive_members(path: Path):
    """Yield (member_name, occurrence_count) for members containing the needle."""
    name = path.name.lower()
    try:
        if name.endswith((".zip", ".whl")):
            with zipfile.ZipFile(path) as zf:
                for info in zf.infolist():
                    if info.is_dir():
                        continue
                    data = zf.read(info)
                    hits = data.count(NEEDLE.encode())
                    if hits:
                        yield info.filename, hits
        elif name.endswith((".tar", ".tar.gz", ".tgz")):
            with tarfile.open(path) as tf:
                for member in tf.getmembers():
                    if not member.isfile():
                        continue
                    fh = tf.extractfile(member)
                    if fh is None:
                        continue
                    hits = fh.read().count(NEEDLE.encode())
                    if hits:
                        yield member.name, hits
        elif name.endswith(".gz"):
            with gzip.open(path, "rb") as fh:
                hits = fh.read().count(NEEDLE.encode())
                if hits:
                    yield "<gzip-body>", hits
    except (OSError, zipfile.BadZipFile, tarfile.TarError, EOFError) as exc:
        yield f"<unreadable: {exc}>", 0


def tracked_files(root: Path, subset: list[str] | None):
    out = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z", *(subset or [])],
        capture_output=True,
        check=True,
    )
    return [p for p in out.stdout.decode().split("\0") if p]


def run_audit(root: Path, rules, subset=None):
    files = tracked_files(root, subset)
    manifest_files = []
    totals = {d: 0 for d in DISPOSITIONS}
    unclassified: list[dict] = []
    total_occurrences = 0

    for rel in files:
        path = root / rel
        if not path.is_file():
            continue
        occurrences = []
        is_archive = rel.lower().endswith(ARCHIVE_SUFFIXES)
        if is_archive:
            for member, hits in scan_archive_members(path):
                if not hits:
                    continue
                occurrences.append(
                    {"member": member, "count": hits, "kind": "archive-member",
                     "disposition": "archive-member"}
                )
        else:
            data = path.read_bytes()
            if NEEDLE.encode() not in data:
                continue
            disposition = classify(rel, rules)
            kind = kind_for(rel)
            for lineno, count in iter_text_occurrences(data):
                entry = {"line": lineno, "count": count, "kind": kind,
                         "disposition": disposition}
                occurrences.append(entry)
                if disposition is None:
                    unclassified.append({"path": rel, "line": lineno})
        if not occurrences:
            continue
        file_hits = sum(o["count"] for o in occurrences)
        total_occurrences += file_hits
        for occ in occurrences:
            if occ["disposition"]:
                totals[occ["disposition"]] += occ["count"]
        manifest_files.append(
            {"path": rel, "sha256": sha256_path(path), "occurrences": occurrences}
        )

    parent_traces = []
    for pattern in PARENT_TRACE_GLOBS:
        for rel in files:
            if fnmatch.fnmatch(rel, pattern):
                parent_traces.append({"glob": pattern, "path": rel,
                                      "sha256": sha256_path(root / rel)})

    manifest = {
        "schema": "bb.rename_occurrence_manifest.v1",
        "needle": NEEDLE,
        "root": str(root),
        "head": subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"],
                               capture_output=True, text=True).stdout.strip(),
        "files_with_occurrences": len(manifest_files),
        "total_occurrences": total_occurrences,
        "totals_by_disposition": totals,
        "unclassified_count": len(unclassified),
        "unclassified": unclassified[:50],
        "baseline_note": (
            "Assessment baseline (2026-08-19 direction doc) measured 517 tracked "
            "files / 1,687 top-level occurrences on an earlier snapshot of this "
            "branch. Deltas against that baseline come from commits landed since "
            "the measurement (campaign evidence refreshes, contract additions) "
            "and from this audit additionally counting archive members and "
            "patch bodies, which the baseline grep excluded."
        ),
        "parent_traces": parent_traces,
        "files": manifest_files,
    }
    return manifest


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    ap.add_argument("--out", required=True, help="manifest JSON output path")
    ap.add_argument("--paths", nargs="*", default=None,
                    help="optional git pathspec subset")
    ap.add_argument("--no-catch-all", action="store_true",
                    help="disable the live-rewrite catch-all rule "
                         "(unclassified occurrences then fail the audit)")
    args = ap.parse_args()

    rules = list(PATH_RULES)
    if not args.no_catch_all:
        rules.append(CATCH_ALL)

    root = Path(args.root).resolve()
    manifest = run_audit(root, rules, args.paths)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=1) + "\n")

    print(f"files_with_occurrences={manifest['files_with_occurrences']}")
    print(f"total_occurrences={manifest['total_occurrences']}")
    for disposition, count in manifest["totals_by_disposition"].items():
        print(f"{disposition}={count}")
    print(f"unclassified={manifest['unclassified_count']}")
    if manifest["unclassified_count"]:
        print("AUDIT FAILED: unclassified occurrences present", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
