"""OMP 18.1.17 stock SDK versus the compiled r2 production conductor.

Run with BB_OMP_TEST_SOURCE_ROOT, BB_OMP_TEST_BUN and NODE_PATH exported:
python -m scripts.compaction_lanes.omp18_lane --out /tmp/omp18-lane
The only model override is a 65536-token window, applied to both sides. The
stock SDK owns tool execution, maintenance checkpoints and deferred handoffs.
Raw bytes are retained. Comparison uses canonical JSON per the integrator's
2026-10-10 decision, removing only guarded, declared summary deviations.
Native Bash elapsed-time lines are the sole environment-only normalization:
the approved anchored regex is applied identically inside tool-result content,
and each report records the substitution count for both sides of every request.
"""
from __future__ import annotations

import argparse
import asyncio
from copy import deepcopy
from datetime import datetime, timezone
import hashlib
import json
import os
import re
from pathlib import Path
import subprocess
from typing import Any

import yaml
from scripts.compaction_lanes.mock_provider import MockProvider

ROOT = Path(__file__).resolve().parents[2]
TARGET_ID = "oh-my-pi-r2@18.1.17"
TARGET_DIR = ROOT / "config/e4_targets/oh_my_pi/18.1.17-r2"
SCENARIOS = ("long_session", "overflow", "large_tool_batch", "final_over_threshold")
WINDOW = 65536
TOOL_ELAPSED_TIME_PATTERN = r"(?m)^Wall time: [0-9]+(?:\.[0-9]+)? seconds$"
TOOL_ELAPSED_TIME = re.compile(TOOL_ELAPSED_TIME_PATTERN)
PROMPT = "Inspect the supplied numbered records, then give the final answer."

# Source SDK setup matches omp_native_tool_worker.ts:524-564. The approved
# target description overlay affects advertisement only, never tool execution.
STOCK_DRIVER = r'''
const input = JSON.parse(await Bun.stdin.text());
const root = input.source;
const { createAgentSession, Settings } = await import(`${root}/packages/coding-agent/src/sdk.ts`);
const { SessionManager } = await import(`${root}/packages/coding-agent/src/session/session-manager.ts`);
const { ModelRegistry } = await import(`${root}/packages/coding-agent/src/config/model-registry.ts`);
const { AuthStorage } = await import(`${root}/packages/ai/src/auth-storage.ts`);
process.env.HOME = input.home;
const settings = await Settings.init({cwd: input.workspace, agentDir: input.scratch,
  inMemory: true, configFiles: [], overrides: {
    "retry.enabled": false, "retry.fallbackChains": {}, "autoContinue.enabled": false,
    "prewalk.enabled": false, "imageUrls.enabled": false, "title.refreshOnReplan": false,
    "tools.maxTimeout": 30, "tools.artifactSpillThreshold": 32768, "edit.fuzzyMatch": true,
    "edit.fuzzyThreshold": 0.95, "edit.enforceSeenLines": true, "edit.autoRepair.enabled": false,
    "edit.blockAutoGenerated": true, "shellMinimizer.enabled": false,
}});
const manager = SessionManager.inMemory(input.workspace);
const authStorage = await AuthStorage.create(":memory:");
const registry = new ModelRegistry(authStorage, `${input.scratch}/models.yml`, {settings});
registry.registerProvider(input.provider, {baseUrl: input.base_url, api: "openai-completions",
  apiKey: "episode-secret", models: [input.model]});
const model = registry.find(input.provider, input.model.id);
const {session} = await createAgentSession({cwd: input.workspace, agentDir: input.scratch,
  authStorage, modelRegistry: registry, model, thinkingLevel: "off",
  toolNames: input.tools, restrictToolNames: true, allowRestrictedCustomTools: false,
  settings, sessionManager: manager, contextFiles: [], skills: [], rules: [], promptTemplates: [],
  slashCommands: [], customTools: [], extensions: [], additionalExtensionPaths: [],
  disableExtensionDiscovery: true, enableMCP: false, enableLsp: false, enableIrc: false,
  skipPythonPreflight: true, hasUI: false, interactivePrompts: false,
  rebindModelAfterDiscovery: false, getApiKey: async () => "episode-secret"});
const descriptions = {};
for (const tool of session.agent.state.tools) {
  const policy = input.descriptions[tool.name];
  let description = tool.description;
  if (new Bun.CryptoHasher("sha256").update(description).digest("hex") !== policy.original_sha256)
    throw new Error(`stock description differs: ${tool.name}`);
  for (const span of policy.removed_spans) {
    if (description.split(span.text).length !== 2) throw new Error("overlay span differs");
    description = description.replace(span.text, "");
  }
  if (new Bun.CryptoHasher("sha256").update(description).digest("hex") !== policy.bounded_sha256)
    throw new Error(`bounded description differs: ${tool.name}`);
  descriptions[tool.name] = description;
}
session.agent.setTools(session.agent.state.tools.map(tool => new Proxy(tool, {
  get(target, key) {
    if (key === "description") return descriptions[target.name];
    const value = Reflect.get(target, key, target);
    return key === "execute" ? value.bind(target) : value;
  },
})));
const events = [];
session.subscribe(event => {
  if (["agent_start", "agent_end", "auto_compaction_start", "auto_compaction_end"].includes(event.type))
    events.push({type: event.type, reason: event.reason, action: event.action,
      skipped: event.skipped, aborted: event.aborted, errorMessage: event.errorMessage,
      committed: Boolean(event.result) || (event.type === "auto_compaction_end" &&
        event.action === "shake" && event.skipped === false && !event.aborted && !event.errorMessage),
      willRetry: event.willRetry});
});
try {
  await session.prompt(input.prompt);
  const result = JSON.stringify({events, messages: session.agent.state.messages,
    settings: settings.getGroup("compaction")});
  await new Promise<void>((resolve, reject) => {
    process.stdout.write(result, error => error ? reject(error) : resolve());
  });
} finally { await session.dispose(); }
'''


def target_config() -> dict[str, Any]:
    return json.loads((TARGET_DIR / "native-config.json").read_bytes())


def scenario_script(scenario: str) -> list[dict[str, Any]]:
    if scenario not in SCENARIOS:
        raise ValueError(scenario)
    low = {"input_tokens": 1000, "output_tokens": 30, "total_tokens": 1030}
    high = {"input_tokens": WINDOW - 1000, "output_tokens": 30, "total_tokens": WINDOW - 970}
    def text(value: str, usage: dict[str, int] = low) -> dict[str, Any]:
        return {"type": "text", "text": value, "usage": usage}
    def batch(index: int, size: int = 1) -> dict[str, Any]:
        # Identical tiny filesystem reads race on completion order. Real shell
        # commands with distinct delays make the batch reproducible without
        # modifying either scheduler or sorting any captured message array.
        name = "read" if size == 1 else "bash"
        return {"type": "response", "tool_calls": [
            {"name": name, "call_id": f"{name}-{index}-{i}",
             "arguments": json.dumps({"i": "Reading numbered records", **(
                 {"path": f"records-{index}-{i}.txt"} if size == 1 else
                 {"command": f"sleep {i + 0.4:.2f}; cat records-{index}-{i}.txt"})})}
            for i in range(size)], "usage": low}
    summary = text("## Goal\nInspect records.\n## Progress\nRead records.\n## Next steps\nFinish inspection.")
    if scenario == "final_over_threshold":
        return [batch(0), text("Inspection complete.", high), summary]
    if scenario == "long_session":
        first = batch(1)
        first["usage"] = high
        return [batch(0), first, summary, text("Inspection complete.", high), summary]
    if scenario == "large_tool_batch":
        large = batch(1, 12)
        large["usage"] = high
        return [batch(0, 12), large, summary, text("Inspection complete.")]
    error = {"type": "error", "error": "context_length_exceeded",
             "message": "Your input exceeds the context window of this model.", "status_code": 400}
    # Default overflow dispatch tries source shake before soft summarization.
    return [batch(0, 12), error, text("Inspection complete.")]


def seed_workspace(workspace: Path) -> None:
    workspace.mkdir(parents=True, exist_ok=True)
    for batch in range(4):
        for i in range(12):
            text = "".join(f"record {batch} file {i} item {j}: value {j * 7919}\n" for j in range(240))
            (workspace / f"records-{batch}-{i}.txt").write_text(text)


def run_stock(workspace: Path, scratch: Path, base_url: str) -> dict[str, Any]:
    config = target_config()
    source = Path(os.environ["BB_OMP_TEST_SOURCE_ROOT"])
    version = json.loads((source / "packages/coding-agent/package.json").read_bytes())["version"]
    if version != "18.1.17":
        raise ValueError(f"Wrong stock version: {version}")
    provenance = json.loads((TARGET_DIR / "tool-surface.json").read_bytes())["native_description_provenance"]
    scratch.mkdir(parents=True, exist_ok=True)
    (scratch / "home").mkdir(exist_ok=True)
    payload = {
        "source": str(source), "workspace": str(workspace), "scratch": str(scratch),
        "home": str(scratch / "home"), "prompt": PROMPT, "base_url": base_url,
        "provider": config["model_registry"]["provider_id"], "tools": config["tool_names"],
        "model": {"id": "model-a", "name": "Model A", "reasoning": False, "input": ["text"],
                  "contextWindow": WINDOW, "maxTokens": config["model_max_tokens"]},
        "descriptions": {name: {"original_sha256": provenance["original_sha256"][name],
            "bounded_sha256": provenance["bounded_sha256"][name],
            "removed_spans": provenance["removed_spans"][name]} for name in config["tool_names"]},
    }
    proc = subprocess.run([os.environ["BB_OMP_TEST_BUN"], "-e", STOCK_DRIVER], input=json.dumps(payload),
                          capture_output=True, text=True, cwd=workspace, timeout=120)
    (scratch / "stock.stderr").write_text(proc.stderr)
    if proc.returncode:
        raise RuntimeError(f"Stock SDK failed ({proc.returncode}): {proc.stderr}")
    return json.loads(proc.stdout)


async def run_bb(workspace: Path, scratch: Path, base_url: str) -> dict[str, Any]:
    from tests.rl.harness import test_omp_native_stream_conductor as h
    from tests.rl.harness import test_pi_0_73_1_compaction as admission
    from breadboard.rl.harness.policy_provider import E4TargetPolicyProjection
    from breadboard.rl.harness.runners.base import thaw_json
    config = target_config()
    controls = yaml.safe_load((TARGET_DIR / "harness.yaml").read_bytes())["policy"]["execution"]["bounded_controls"]
    profile = h.OpenAICompletionsProviderProfile(model="model-a", scoped_credential="episode-secret", base_url=base_url,
        context_window=WINDOW, max_output_tokens=config["model_max_tokens"], caller_headers={},
        request_policy={"mode": "streaming", "include_usage": True, "max_token_field": "max_completion_tokens", "strict_tools": None, "enable_thinking": None},
        capabilities={"supports_store": True, "supports_max_completion_tokens": True})
    cas = h.FilesystemCAS(scratch / "cas")
    try:
        compiled = h.compile_e4_harness(h.load_e4_target(TARGET_ID), {}, {
            "version": 2, "profile": {"name": "omp18-compaction-lane"}, "workspace": {"root": "workspace"},
            "provider_tools": {"use_native": True, "api_variant": "chat_completions"},
            "providers": {"default_model": "model-a", "models": [{"id": "model-a", "adapter": "openai",
                "context_length": WINDOW, "route_handle_id": "route-a", "credential_handle_id": "credential-a", "params": {},
                "response_policy": {"schema_version": "bb.provider_native_response_policy.v1", "consumer_id": h.OMP_RESPONSE_CONSUMER_ID,
                    "provider_profile_digest": h.profile_identity_digest(profile), "max_response_bytes": 1048576, "max_stream_fragments": 10000}}]}},
            cas=cas, options=h._options(), request_schema_version="bb.rl.headless-run-request.v2")
        manifest = compiled.manifest
        projection = E4TargetPolicyProjection.from_compiled(manifest)
    finally:
        cas.close()
    observation = h._observation(provider_id="openai", model_id="model-a", capabilities=h._policy_capabilities(
        request_features=["max_completion_tokens", "n", "store", "stream_options", "streaming"]))
    grants = tuple(h._tool_grant(name) for name in sorted(config["tool_names"]))
    plan = h._plan(observation=observation, semantics=manifest.semantic.to_canonical_obj(), tools=grants,
        policy_slot_ids=("model:model-a",), implementation_digest=h.CONDUCTOR_IMPLEMENTATION_DIGEST,
        limit_updates={"max_turns": controls["max_model_calls"], "action_timeout_ms": controls["single_tool_wall_seconds"] * 1000,
                       "observation_bytes": controls["raw_evidence_bytes_per_outcome"],
                       "transcript_bytes": controls["max_model_calls"] * controls["raw_evidence_bytes_per_outcome"]})
    base = plan.base_compiled.model_dump(mode="python")
    base.update(manifest_digest="sha256:" + hashlib.sha256(manifest.canonical_bytes()).hexdigest(), compiler_input_digest=manifest.inputs.compiler_input_digest)
    data = plan.model_dump(mode="python")
    data["base_compiled"] = h.c.CompiledArtifactIdentity.model_validate(base)
    plan = h.c.EffectiveExecutionPlan.model_validate(data)
    class Port(h._OMPWorkspacePort):
        async def invoke_native_phase(self, operation: str, payload: Any, *, timeout_ms: int, package_subpath: str | None = None) -> Any:
            body = thaw_json(payload)
            if operation == "initialize":
                inputs = self.native_runtime_inputs(input_names=("cwd", "home", "current_date", "package_dir"), package_subpath=package_subpath)
                body.update(workspace=str(workspace), scratch=str(scratch), package_dir=inputs["package_dir"], runtime_inputs=inputs)
                body["route_classifier"]["source_root"] = self.worker.spec.source_root
            result = await asyncio.to_thread(self.worker.phase, operation, body)
            self.phase_log.append({"operation": operation, "payload": body, "result": deepcopy(result)})
            return result
    port = Port(workspace, scratch, tuple(h.RunnerToolBinding(t.tool_id, t.implementation_digest, t.capability_ids) for t in grants), datetime.now(timezone.utc).date().isoformat())
    from breadboard.rl.harness.lease_envelope import RuntimeContainment
    from tests.rl.harness.v2_service_fixtures import signed_containment_receipt
    port.containment = RuntimeContainment.ATTESTED
    port.containment_lease_id = admission.CONDUCTOR_TEST_LEDGER.record.lease_id
    port.containment_receipt = signed_containment_receipt(port.containment_lease_id, "sandbox", admission.CONDUCTOR_TEST_AUTHENTICATOR)
    port.declared_workspace = str(workspace)
    (scratch / "home").mkdir(parents=True, exist_ok=True)
    request = h.RunnerOpenRequest(episode_id="omp18-lane", effective_plan=plan)
    client = h.EpisodeOpenAICompletionsPolicyClient(episode_id=request.episode_id, effective_plan_digest=plan.canonical_digest(), observation=observation, profile=profile, target_projection=projection, timeout_seconds=45)
    sink = admission._Events()
    session = await h.ConductorAdapter(h.CONDUCTOR_RUNTIME_ABI, containment_authenticator=admission.CONDUCTOR_TEST_AUTHENTICATOR,
        admitted_lease_ledger=admission.CONDUCTOR_TEST_LEDGER).open(request, policy=h.PolicyRuntimeBinding(request, client),
            workspace=port, cancellation=admission._Cancellation(), events=sink)
    try:
        result = await session.run(h.ConductorRunRequest(task_input={"prompt": PROMPT}, context={}))
        return {"trace": thaw_json(result.response["replay_trace"]), "phases": port.phase_log,
                "termination": result.termination.value}
    except Exception as error:
        (scratch / "failure.json").write_text(json.dumps({
            "error": str(error), "phases": port.phase_log,
        }, indent=2))
        raise
    finally:
        await session.close()
        await asyncio.to_thread(port.worker.stop)
        await client.close()


def remove_fields(raw: bytes, fields: set[str]) -> bytes:
    """Remove top-level JSON members without reserializing retained bytes."""
    text = raw.decode("utf-8")
    decoder = json.JSONDecoder()
    pos = 1
    members = []
    while True:
        start = pos
        while text[pos].isspace():
            pos += 1
        if text[pos] == "}":
            break
        key, end = decoder.raw_decode(text, pos)
        pos = end
        while text[pos].isspace():
            pos += 1
        if text[pos] != ":":
            raise ValueError("Invalid JSON member")
        pos += 1
        while text[pos].isspace():
            pos += 1
        _, end = decoder.raw_decode(text, pos)
        pos = end
        while text[pos].isspace():
            pos += 1
        members.append((key, text[start:pos]))
        if text[pos] == "}":
            break
        if text[pos] != ",":
            raise ValueError("Invalid JSON separator")
        pos += 1
    return ("{" + ",".join(value for key, value in members if key not in fields) + text[pos:]).encode()


def canonical_json(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False).encode()


def guarded_summary_fields(stock: dict[str, Any], bb: dict[str, Any], main: dict[str, Any], budget: int | None, deviations: list[str]) -> set[str]:
    fields: set[str] = set()
    if stock.get("tool_choice") == "none":
        # session-handoff.ts uses a side-stream with the live model's tools
        # and output cap. These are equal bytes, not admitted deviations.
        if canonical_json(stock.get("tools")) != canonical_json(main["tools"]) or canonical_json(bb.get("tools")) != canonical_json(main["tools"]):
            raise ValueError("Handoff tools differ from episode tools")
        if type(stock.get("max_completion_tokens")) is not int or type(bb.get("max_completion_tokens")) is not int or stock.get("max_completion_tokens") != main["max_completion_tokens"] or bb.get("max_completion_tokens") != main["max_completion_tokens"]:
            raise ValueError("Handoff token cap differs from live model")
        if bb.get("tool_choice") != "none":
            raise ValueError("Handoff tool_choice differs from stock")
        return fields
    if "compaction_summary_episode_tools" in deviations:
        if "tools" in stock or canonical_json(bb.get("tools")) != canonical_json(main["tools"]):
            raise ValueError("Summary tools differ from admitted values")
        fields.add("tools")
    if "compaction_summary_max_tokens" in deviations:
        if type(budget) is not int or type(stock.get("max_completion_tokens")) is not int or type(bb.get("max_completion_tokens")) is not int or stock.get("max_completion_tokens") != budget or bb.get("max_completion_tokens") != main["max_completion_tokens"]:
            raise ValueError("Summary token cap differs from admitted budget")
        fields.add("max_completion_tokens")
    # tool_choice is stock behavior, not a deviation. Never remove it.
    if stock.get("tool_choice") != bb.get("tool_choice"):
        raise ValueError("Summary tool_choice differs from stock")
    return fields


def normalize_tool_elapsed_time(payload: dict[str, Any]) -> int:
    count = 0
    for message in payload.get("messages", []):
        if message.get("role") == "tool" and isinstance(message.get("content"), str):
            message["content"], substitutions = TOOL_ELAPSED_TIME.subn("Wall time: <elapsed> seconds", message["content"])
            count += substitutions
    return count


def compare_requests(stock: list[Any], bb: list[Any], phases: list[Any], deviations: list[str], used_deviations: set[str] | None = None, timing_substitutions: list[dict[str, int]] | None = None) -> list[Any]:
    diffs = []
    budgets = []
    for phase in phases:
        result = phase["result"]
        if phase["operation"] == "prepare_compaction" and result.get("kind") == "compaction_prepared":
            budgets.extend(result[key].get("max_tokens") for key in ("summary_request", "turn_prefix_request") if result.get(key))
        elif result.get("kind") == "compaction_followup_request":
            budgets.append(result["request"].get("max_tokens"))
    main = bb[0]["json"] if bb else {}
    budget_iter = iter(budgets)
    for i in range(max(len(stock), len(bb))):
        if i >= len(stock) or i >= len(bb):
            diffs.append({"index": i, "type": "request_count"})
            continue
        left = bytes.fromhex(stock[i]["raw_body_bytes"])
        right = bytes.fromhex(bb[i]["raw_body_bytes"])
        if stock[i]["json"].get("tools") is None or stock[i]["json"].get("tool_choice") == "none" or bb[i]["json"].get("tool_choice") == "none":
            budget = next(budget_iter, None)
            try:
                fields = guarded_summary_fields(stock[i]["json"], bb[i]["json"], main, budget, deviations)
                if used_deviations is not None:
                    if "tools" in fields:
                        used_deviations.add("compaction_summary_episode_tools")
                    if "max_completion_tokens" in fields:
                        used_deviations.add("compaction_summary_max_tokens")
                left, right = remove_fields(left, fields), remove_fields(right, fields)
            except ValueError as error:
                diffs.append({"index": i, "type": "deviation_guard", "message": str(error)})
                continue
        left_payload, right_payload = json.loads(left), json.loads(right)
        counts = {"index": i, "stock": normalize_tool_elapsed_time(left_payload),
                  "bb": normalize_tool_elapsed_time(right_payload)}
        if timing_substitutions is not None:
            timing_substitutions.append(counts)
        left = canonical_json(left_payload)
        right = canonical_json(right_payload)
        if left != right:
            offset = next((n for n, (a, b) in enumerate(zip(left, right)) if a != b), min(len(left), len(right)))
            diffs.append({"index": i, "type": "byte_diff", "first_offset": offset,
                "stock_sha256": hashlib.sha256(left).hexdigest(), "bb_sha256": hashlib.sha256(right).hexdigest(),
                "stock_excerpt": left[max(0, offset-40):offset+140].decode(), "bb_excerpt": right[max(0, offset-40):offset+140].decode()})
    return diffs


def run_scenario(out: Path, scenario: str) -> dict[str, Any]:
    out.mkdir(parents=True, exist_ok=True)
    workspace = out / "workspace"
    seed_workspace(workspace)
    stock_server = MockProvider(scenario_script(scenario), out / "stock.requests.jsonl")
    bb_server = MockProvider(scenario_script(scenario), out / "bb.requests.jsonl")
    stock_server.start()
    bb_server.start()
    try:
        stock = run_stock(workspace, out / "stock-runtime", stock_server.base_url + "/v1")
        bb = asyncio.run(run_bb(workspace, out / "bb-runtime", bb_server.base_url + "/v1"))
    finally:
        stock_server.stop()
        bb_server.stop()
    requests = {"stock": stock_server.engine.recorded_requests, "bb": bb_server.engine.recorded_requests}
    policy = yaml.safe_load((TARGET_DIR / "harness.yaml").read_bytes())["policy"]
    deviations = [d["id"] for d in policy["deviations"]]
    controls = policy["execution"]["bounded_controls"]
    compactions = {"stock": sum(e["type"] == "auto_compaction_end" and e["committed"] for e in stock["events"]),
                   "bb": sum(p["result"].get("kind") == "compaction_finalized" for p in bb["phases"])}
    used_deviations: set[str] = set()
    timing_substitutions: list[dict[str, int]] = []
    diffs = compare_requests(requests["stock"], requests["bb"], bb["phases"], deviations, used_deviations, timing_substitutions)
    report = {"target": TARGET_ID, "scenario": scenario, "overrides": {"context_window": {"production": target_config()["context_window"], "lane": WINDOW}},
        "comparison_basis": "canonical JSON, sort_keys=True, separators=(',', ':'), ensure_ascii=False",
        "bounded_controls": controls,
        "admission_transcript_bytes": controls["max_model_calls"] * controls["raw_evidence_bytes_per_outcome"],
        "compaction_count_basis": "successful native auto_compaction_end, including non-skipped shake; BB compaction_finalized",
        "environment_normalization": {"pattern": TOOL_ELAPSED_TIME_PATTERN,
            "scope": "tool-result message content strings only", "substitutions": timing_substitutions},
        "raw_byte_difference_indices": [i for i, (a, b) in enumerate(zip(requests["stock"], requests["bb"]))
                                        if a["raw_body_bytes"] != b["raw_body_bytes"]],
        "request_counts": {side: len(rows) for side, rows in requests.items()}, "compaction_counts": compactions,
        "diffs": diffs,
        "deviations_used": sorted(used_deviations), "deviations_admitted": deviations,
        "stock": stock, "bb": bb, "requests": requests}
    (out / "lane_report.json").write_text(json.dumps(report, indent=2))
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--scenario", choices=SCENARIOS)
    args = parser.parse_args()
    reports = [run_scenario(args.out / scenario, scenario) for scenario in ([args.scenario] if args.scenario else SCENARIOS)]
    print(json.dumps([{k: r[k] for k in ("scenario", "request_counts", "compaction_counts", "diffs", "deviations_used")} for r in reports], indent=2))
    if any(r["diffs"] for r in reports):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
