"""Optimization helpers and typed substrate primitives."""

from .backend import (
    OBJECTIVE_DIRECTIONS,
    CandidatePortfolio,
    MutationPolicyInput,
    MutationBounds,
    MutationProposal,
    ObjectiveVector,
    OptimizationExecutionContext,
    PortfolioEntry,
    ReflectionDecision,
    ReflectionFinding,
    ReflectionPolicyInput,
    ReflectiveParetoBackend,
    ReflectiveParetoBackendRequest,
    ReflectiveParetoBackendResult,
    TypedOverlayMutationPolicy,
    WrongnessGuidedReflectionPolicy,
    run_reflective_pareto_backend,
    validate_bounded_candidate,
)
from .context import (
    EnvironmentSelector,
    MCPContextRequirement,
    OptimizationRuntimeContext,
    RuntimeCompatibilityIssue,
    RuntimeCompatibilityResult,
    SandboxContextRequirement,
    ServiceContextRequirement,
    ToolPackContext,
    ToolRequirement,
)
from .gepa_guardrails import validate_prompt_mutation
from .dataset import (
    CorrectnessRationale,
    GroundTruthPackage,
    OptimizationDataset,
    OptimizationSample,
)
from .diagnostics import DiagnosticBundle, DiagnosticEntry
from .evaluation import EvaluationRecord
from .examples import (
    build_codex_dossier_dataset_example,
    build_codex_dossier_dataset_example_payload,
    build_codex_dossier_backend_example,
    build_codex_dossier_backend_example_payload,
    build_codex_dossier_evaluation_example,
    build_codex_dossier_evaluation_example_payload,
    build_codex_dossier_example,
    build_codex_dossier_example_payload,
    build_codex_dossier_runtime_context_examples,
    build_codex_dossier_runtime_context_examples_payload,
    build_codex_dossier_promotion_examples,
    build_codex_dossier_promotion_examples_payload,
)
from .optuna_config import load_optuna_config
from .promotion import (
    ALLOWED_TRANSITIONS,
    PROMOTION_STATES,
    GateResult,
    PromotionDecision,
    PromotionEvidence,
    PromotionRecord,
    ReplayConformanceGateInput,
    SupportEnvelopeGateInput,
    build_promotion_evidence,
    create_promotion_record,
    evaluate_conformance_gate,
    evaluate_promotion_gates,
    evaluate_replay_gate,
    evaluate_support_envelope_gate,
    promote_candidate,
)
from .substrate import (
    ArtifactRef,
    CandidateBundle,
    CandidateChange,
    MaterializedCandidate,
    MutableLocus,
    OptimizationInvariant,
    OptimizationTarget,
    SupportEnvelope,
    materialize_candidate,
)
from .trajectory_ir import TrajectoryEpisode, TrajectoryStep, build_stub_episode
from .wrongness import WrongnessReport

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ArtifactRef",
    "CandidateBundle",
    "CandidateChange",
    "CandidatePortfolio",
    "CorrectnessRationale",
    "DiagnosticBundle",
    "DiagnosticEntry",
    "EnvironmentSelector",
    "EvaluationRecord",
    "GateResult",
    "GroundTruthPackage",
    "MCPContextRequirement",
    "MaterializedCandidate",
    "MutableLocus",
    "MutationBounds",
    "MutationPolicyInput",
    "MutationProposal",
    "OBJECTIVE_DIRECTIONS",
    "ObjectiveVector",
    "OptimizationDataset",
    "OptimizationExecutionContext",
    "OptimizationInvariant",
    "OptimizationRuntimeContext",
    "OptimizationSample",
    "OptimizationTarget",
    "PROMOTION_STATES",
    "PortfolioEntry",
    "PromotionDecision",
    "PromotionEvidence",
    "PromotionRecord",
    "ReflectionDecision",
    "ReflectionFinding",
    "ReflectionPolicyInput",
    "ReplayConformanceGateInput",
    "ReflectiveParetoBackend",
    "ReflectiveParetoBackendRequest",
    "ReflectiveParetoBackendResult",
    "RuntimeCompatibilityIssue",
    "RuntimeCompatibilityResult",
    "SandboxContextRequirement",
    "ServiceContextRequirement",
    "SupportEnvelope",
    "SupportEnvelopeGateInput",
    "ToolPackContext",
    "ToolRequirement",
    "TrajectoryEpisode",
    "TrajectoryStep",
    "TypedOverlayMutationPolicy",
    "WrongnessGuidedReflectionPolicy",
    "WrongnessReport",
    "build_codex_dossier_backend_example",
    "build_codex_dossier_backend_example_payload",
    "build_codex_dossier_dataset_example",
    "build_codex_dossier_dataset_example_payload",
    "build_codex_dossier_evaluation_example",
    "build_codex_dossier_evaluation_example_payload",
    "build_codex_dossier_example",
    "build_codex_dossier_example_payload",
    "build_codex_dossier_promotion_examples",
    "build_codex_dossier_promotion_examples_payload",
    "build_codex_dossier_runtime_context_examples",
    "build_codex_dossier_runtime_context_examples_payload",
    "build_promotion_evidence",
    "build_stub_episode",
    "create_promotion_record",
    "evaluate_conformance_gate",
    "evaluate_promotion_gates",
    "evaluate_replay_gate",
    "evaluate_support_envelope_gate",
    "load_optuna_config",
    "materialize_candidate",
    "promote_candidate",
    "run_reflective_pareto_backend",
    "validate_bounded_candidate",
    "validate_prompt_mutation",
]
